### ISSUE TITLE
Filter Amazon devices from Amazon domain

### ISSUE THREAD

**Issue by ThatJeffGuy** [letsblockit/letsblockit#146]
### What website(s) would this filter apply to?

amazon.ca amazon.com etc

### What content should be blocked?

On the Amazon Website, there's a deals section. They manage to put their devices in to each line so that you only see three or four products instead of 5. It's excessive. How many Echo's does one need in their house?

They also splice them into search results - the other day I searched for black plastic zip ties, and had 3 different versions of the Echo Dot show up as valid results.

![d3V32RlsBs](https://user-images.githubusercontent.com/49243483/168083487-5392aa8a-541e-4c2e-9167-cfc8273c411a.png)

### What options should be offered?

1. Remove All sponsored devices - blacklist all devices (for Google and Apple Ecosystem homes)
2. Allow one device per page of any kind, first one that Amazon decides
3. Whitelist audio only devices - no TV's, displays, etc.
4. Whitelist only video devices - no Echo's, etc.

### Did you write a custom uBlock filter already?

I R smooth brane, don't know how :(

### Additional notes

What kind of dinosaur is always on the run from the police?

Doyouthinkhesaurus

**Comment by xvello** [comment]
Hello @ThatJeffGuy, thanks for your idea.

That looks pretty specific, unless someone steps up to maintain a list of these products, it will be difficult to keep it up to date.

Would a template to configure product listing matching a list of words / regexp work for this use case? We'll need to check the different layout types (deals, search, categories...), hopefully there are not too many.

**Comment by ThatJeffGuy** [comment]
I don't think it should be difficult to implement, but then again, I'm a electrical engineer, not a software engineer like yourself lol

They're all called the same model, just different version numbers - Echo Dot 4th Gen, Echo Show 2nd Gen, etc.

**Comment by xvello** [comment]
Sorry for the delay @ThatJeffGuy, I need to also think about non-english countries, where the device naming might be different.

I think I'll use the presets feature (used in https://letsblock.it/filters/search-results) to split the work in two:
  - a "Hide articles on Amazon" template that allows users to match any product, by word match and/or regular expression. It will need rules for a lot of different pages
  - presets for Amazon devices and Amazon Basics (any other preset comes to mind?)

If you have some time to help, could you please give me:

- a list of device names you'd like to see blocked
- a list of pages the filter should be active on (its not only search, there's also the "related products" carousel on product pages for example)

**Comment by xvello** [comment]
Filter is deployed, don't hesitate to suggest other product presets, or signal pages where the filter should act.

**Comment by ThatJeffGuy** [comment]
It would appear, likely because Prime Day is coming, that they've changed things significantly. Double checked and even deleted and re-added, in case my filters were out of date, but no change.

![L4YQOvcx7F](https://user-images.githubusercontent.com/49243483/177785670-4a59d58a-2ab5-4c71-b4be-e497a4cfe89a.png)

**Comment by xvello** [comment]
Thanks for the ping @ThatJeffGuy, it's just a change in their class names. Could you please confirm that the following rule works for you?

> ##div.deals-react-app div[class^=DealContent]:has-text(/\bEcho (Dot|Show|Studio|Sub|Buds|Auto|Flex)\b/):upward(div[class^=DealGridItem-module__dealItem])

I'll update the templates.

**Comment by ThatJeffGuy** [comment]
Seems to have cleaned it up, but a few more snuck through.

![4cK2UBZwHR](https://user-images.githubusercontent.com/49243483/177862737-8705e876-5abc-4b3f-b071-dcc795dc4571.png)

**Comment by ThatJeffGuy** [comment]
Yep, refresh got the 4th gen gone, but still one more I can see:

![pY1XrULPvC](https://user-images.githubusercontent.com/49243483/177866001-6c1fff59-517c-4fcc-ab3e-93fc11beb67b.png)

**Comment by xvello** [comment]
Fire tablets are not in the current amazon products presets, so that's a different issue.
Could you please open a separate issue with products I missed (ideally with a product page link), so that I expand it?

**Comment by ThatJeffGuy** [comment]
Yep, sorry for cross contaminating threads. Will start it tomorrow at work 😊

Thanks!

_┌П︵Î∏П┐_
Jeff Wilton
________________________________

**Comment by ThatJeffGuy** [comment]
Luckily, I'm in the office all this week so I can you this info relatively quickly.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
