### ISSUE TITLE
support the Duckduckgo 'lite' and 'HTML' search engines

### ISSUE THREAD

**Issue by 07416** [letsblockit/letsblockit#156]
### What filter does this issue target?

https://letsblock.it/filters/search-results

### What changes should be made?

add support for:

https://html.duckduckgo.com/html/?q=tmp
https://lite.duckduckgo.com/lite/?q=tmp

Could be merged with the current Duckduckgo filters.

https://duckduckgo.com/tty/#q=tmp also exists, if supporting is feasible.

**Comment by xvello** [comment]
Hello @07416, thanks for your suggestion.

Do you actually use these alternate interfaces, or are you suggesting them to be exhaustive? Seeing as the copycat presets generate thousands of rules already, I don't want to double / triple this (and have every user incur the additional evaluation cost) if they are not useful to anyone.

**Comment by 07416** [comment]
Yes, I use the lite DDG search and both mobile and desktop (especially useful on the former to conserve battery) and mainly only switch to the main DDG for images at the time. The lite search page seems to be measured in kilobytes and appears to load in under half a second on my machine,  with Dark Reader and various other extensions which run on every page.

A separate checkbox for the lite and HTML filters seems optimal, if you ever plan to add support.

'tty' is mainly a novelty for most I assume.

**Comment by xvello** [comment]
Thanks for your response.

After looking at it a second time, because these are separate subdomains (`html.duckduckgo.com` and `lite.duckduckgo.com`, rules targeting these versions will be ignored when visiting the main domain. I'll look into creating rules and will update this issue!

**Comment by BPower0036** [comment]
```
lite.duckduckgo.com##.result-link[href*="fileinfo.com"]:upward(tr)
lite.duckduckgo.com##.result-link[href*="fileinfo.com"]:upward(tr) + tr
lite.duckduckgo.com##.result-link[href*="fileinfo.com"]:upward(tr) + tr + tr 
```
For  `https://html.duckduckgo.com/` and `https://duckduckgo.com/` the same rule can be used

**Comment by xvello** [comment]
@07416 it's released on https://letsblock.it/filters/search-results, don't hesitate to reopen the issue if you notice quirks.
