### ISSUE TITLE
Remove Youtube Shorts logo only

### ISSUE THREAD

**Issue by AhoyThere** [letsblockit/letsblockit#196]
Hello,

sorry if my request should have gone somewhere else or if I'm doing it wrong but I so far haven't really figured out how to post something properly on Github.

I found your youtube-shorts script through a Google search. I was looking for a way to remove that white/red Shorts logo from preview pictures in Youtube's search. I do only want to remove that logo, not the videos/results.

I tried picking it using uBlock but it removes the whole preview picture instead. Then I tried every line from your code but neither removed the logo (or the logo came back after starting to scroll through the results).

Is there a way to remove that logo? Thanks in advance.

**Comment by xvello** [comment]
Hello @AhoyThere,
The following rule should do the trick on desktop:
> www.youtube.com##ytd-thumbnail-overlay-time-status-renderer[overlay-style="SHORTS"]

It will match and hide the thumbnail overlay, but the duration information is not available anyway.

**Comment by AhoyThere** [comment]
Yay, it works. Thank you very much.  :)
