### ISSUE TITLE
YouTube Shorts - not blocked in List view of subscriptions

### ISSUE THREAD

**Issue by kiriya-aoi** [letsblockit/letsblockit#198]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

![image](https://user-images.githubusercontent.com/107003898/175653632-2a4a5807-727f-4e8a-ba4f-f8fe812eb07c.png)

### Did you write a uBlock filter solving this?

`www.youtube.com##ytd-browse ytd-item-section-renderer:has(span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"])`

**Comment by xvello** [comment]
Thanks @kiriya-aoi. That was also discussed [on reddit](https://www.reddit.com/r/uBlockOrigin/comments/vecnuv/youtube_premiers_appearing_in_sub_box_again/) for the upcoming lives filter.

I'm updating all the relevant filters in https://github.com/letsblockit/letsblockit/pull/200

**Comment by xvello** [comment]
This filter breaks the grid view when videos are grouped by date, so I have reverted it while I look for a fix.

**Comment by kiriya-aoi** [comment]
Ah, it actually deletes the subscription view chooser (pictured) too, if a short is first in the list.
![image](https://user-images.githubusercontent.com/34067059/175795605-db1430aa-627b-4b1e-8b05-e49ade18ca98.png)

If I limit the scope, I can eliminate the videos themselves in list view (but not the title of the channel that released the short).

`www.youtube.com##ytd-browse ytd-expanded-shelf-contents-renderer:has(span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"])`

Which gives this result for shorts in list view:
![image](https://user-images.githubusercontent.com/34067059/175795907-a29f4edd-6688-4130-91a0-bc2296ebaa7a.png)
It doesn't affect the behavior in grid view, but it's also not good enough to really recommend.

**Comment by xvello** [comment]
My concern was also that if a channel posted two videos consecutively they would be groupped in the same `ytd-item-section-renderer`, meaning one short would hide the "full video" posted alongside it. On my account, it does not seem to be the case, each video has their own section:
![image](https://user-images.githubusercontent.com/6241083/175806380-d68230c6-5ff5-412b-90bd-71a5ddefbb6b.png)

That might change in the future, in which case we'll need to rollback our change, but for now we are safe with hiding the full `ytd-item-section-renderer`, we just need to find a way to differentiate between grid and list view. Unfortunately, the toplevel elements have no semantic difference, but the `ytd-thumbnail` item does have different classes. We should be able to get away with rules in the following form

```
www.youtube.com##ytd-browse PARENT_TO_FIND span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"]:upward(ytd-grid-video-renderer)
www.youtube.com##ytd-browse PARENT_TO_FIND span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"]:upward(ytd-item-section-renderer)
```

**Comment by xvello** [comment]
Let's go with the following rules:

! For list view
www.youtube.com##ytd-browse ytd-video-renderer span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"]:upward(ytd-item-section-renderer)
! For grid view
www.youtube.com##ytd-browse ytd-grid-video-renderer span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"]:upward(ytd-grid-video-renderer)

I'll prepare a PR to update the shorts filter, and work on the other filters if nothing breaks.

**Comment by xvello** [comment]
Heya @kiriya-aoi I merged #203 that should improve the situation without regression on the grid list.

Please try [refreshing your list](https://letsblock.it/help/refresh-list) and tell me whether it works for for you!

**Comment by kiriya-aoi** [comment]
It does appear to work in all of my usage. No noticeable side-effects, aside from the one I mentioned in the first line of https://github.com/letsblockit/letsblockit/issues/198#issuecomment-1166394554.

**Comment by xvello** [comment]
Thanks for your response @kiriya-aoi.
I think this is an acceptable tradeoff. An alternative would be to enforce never hiding the first row, but that would probably be more confusing.
