### ISSUE TITLE
Write and review documentation for self-hosting

### ISSUE THREAD

**Issue by xvello** [letsblockit/letsblockit#201]
Now that [all the blocker issues](https://github.com/letsblockit/letsblockit/issues?q=+is%3Aissue+label%3Aself-hosting+) for self-hosting have been closed, it's time for the most difficult part: documentation.

The LBI setup is pretty easy, just set `LETSBLOCKIT_AUTH_METHOD=proxy` and `LETSBLOCKIT_AUTH_PROXY_HEADER_NAME` to the name of the header the reverse proxy will inject. The complexity lies in the proxy configuration to:

- ensure requests to `/list/*` pass through without authentication
- inject a unique user property (username, UUID, email...) in a header, and ensure that header cannot be forged.

Unless people step up to write and maintain them, I won't be publishing an official docker compose or k8s chart, but we could document some of the following auth setups:

- multi-user http basic auth with traefik
- mono-user http basic auth with nginx (it does not support injecting the username in a header)
- oauth2 auth via oauth2-proxy
- kratos auth with Ory Cloud (self-hosted Kratos should work, but is non-trivial to setup)

If you are willing to test these installation methods, or interested in others, please comment on this issue!

**Comment by alexanderadam** [comment]
My is currently pretty packed but I try my best to support once I have some time again.
You're just to fast in implementing these features. :wink:
