### ISSUE TITLE
New filter suggestion: Already watched videos on Youtube

### ISSUE THREAD

**Issue by Markussss** [letsblockit/letsblockit#205]
### What website(s) would this filter apply to?

youtube.com

### What content should be blocked?

Youtube often shows videos that you have already watched to the end or videos that you have started watching but stopped watching. These will be displayed with a red bar underneath the thumbnail to indicate how much of the video has been watched. These should be blocked.

### What options should be offered?

I can't think of any options for this filter.

### Did you write a custom uBlock filter already?

```
www.youtube.com##ytd-rich-item-renderer:has(ytd-thumbnail-overlay-resume-playback-renderer)
www.youtube.com##ytd-compact-video-renderer:has(ytd-thumbnail-overlay-resume-playback-renderer)
```

### Additional notes

I'm suggesting this because I have been using it for a while in my own personal block list.

**Comment by xvello** [comment]
Hello @Markussss, thanks a lot, that's a great idea. I'll work on creating the template for it.
