### ISSUE TITLE
SoundCloud - Hide reposts by certain artists (from "stream" page)

### ISSUE THREAD

**Issue by krisu5** [letsblockit/letsblockit#208]
### What website(s) would this filter apply to?

https://soundcloud.com/stream

### What content should be blocked?

Based of user query, any artist's repost on the "stream" page.

[Screenshot example: repost block for artist called IMANU](https://user-images.githubusercontent.com/3540275/177042466-e8eead9e-719b-4add-b133-2a69946ba7f7.png).

I have also filters for only artist pages and global (anywhere in SoundCloud) if you want to implement those somehow.

### What options should be offered?

Option to write artist's name to block reposts, on the stream page at least.

Maybe possibility to pick option for blocking only on artist pages or globally on SoundCloud.

**Instructions:** copy the artist name from the page as is, not from URL.

### Did you write a custom uBlock filter already?

Only in "Stream" page:
```
soundcloud.com##.soundList__item .activity:has(.soundContext__repost):has(.soundContext__usernameLink:has-text(CHANGE-THIS-TO-ARTIST-NAME))
```

Only in artist page:
```
soundcloud.com##.soundList__item:has(.sc-ministats-reposts[title="Reposted by CHANGE-THIS-TO-ARTIST-NAME"])
```

Globally:
```
soundcloud.com##.soundList__item .sound[aria-label$="reposted by CHANGE-THIS-TO-ARTIST-NAME"]
```

### Additional notes

https://soundcloud.com/stream needs login and artists to follow.

Artist pages can be viewed without login, eg. https://soundcloud.com/imanumusic

**Comment by xvello** [comment]
Heya @krisu5, thanks a lot for your contribution, I'll look right into it!
