### ISSUE TITLE
Hide map and places listed at top of Google search page

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#222]
### What website(s) would this filter apply to?

https://www.google.com/search?q=50mm+clear+silicone+food+hose&biw=1920&bih=929&ei=0XDSYsvhA4vvgQaWvb3QDg&ved=0ahUKEwiLjsiP-fz4AhWLd8AKHZZeD-oQ4dUDCA4&uact=5&oq=50mm+clear+silicone+food+hose&gs_lcp=Cgdnd3Mtd2l6EAM6BwgAEEcQsANKBAhBGABKBAhGGABQtQdYhA1ggxBoAXABeACAAewBiAHkCJIBAzItNZgBAKABAcgBAsABAQ&sclient=gws-wiz

### What content should be blocked?

Hide map and places listed at top of Google search page.
![image](https://user-images.githubusercontent.com/32925097/179346737-822f9f13-8ef6-4b19-a57f-6c77abcec9ca.png)

### Did you write a custom uBlock filter already?

The following had effect on the above page, but I'm not sure if it would always work or if it's the best way to do this.

! Hide Map stuff
!www.google.com##.M8OgIe

**Comment by xvello** [comment]
Heya @3DWORX-SA, I am working on rules to hide maps and other "rich content" boxes that are inline with the results, see https://github.com/letsblockit/letsblockit/issues/219#issuecomment-1185845313, but this is a different beast: the map is outside of `#rso`, in it's own toplevel element. The following rule matches it, but it probably has side-effects I need to test before including it in the template:
```
google.*###rcnt > div:not([id]) > div:last-of-type
```

**Comment by xvello** [comment]
Just released a new version with a more reliable version of that rule:

>   google.*###rcnt > div:first-of-type:not([id]) > div:has(g-more-link,g-scrolling-carousel)

The rule I posted earlier breaks the shopping search.
