### ISSUE TITLE
Update YouTube Shorts filters to work on mobile

### ISSUE THREAD

**Issue by greggorievich** [letsblockit/letsblockit#230]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

When I tested the filters to remove youtube shorts using uBlock Origin on Firefox Nightly on Android, it does not appear to block shorts. It would be nice if the filters were updated to work for YouTube's mobile site. 

### Did you write a uBlock filter solving this?

Nope! I am probably far too stupid for this, my skill with uBO sort of peters out somewhere around "use the element picker". 

### Additional notes

Issue created per suggestion from /u/ollev on Reddit.

**Comment by xvello** [comment]
Hello @greggorievich, thanks for reporting this. YouTube has indeed a whole different markup for mobile browsers, so it needs a different set of rules. I have been putting it off for a bit because there's many YouTube filters now, but I can start with shorts first, then work on the rest.

Will try to get something testable this weekend!

**Comment by xvello** [comment]
Heya @greggorievich, the following rules should do the trick (you can add them as custom filters and sync your list):

```
m.youtube.com##ytm-pivot-bar-renderer div.pivot-shorts:upward(ytm-pivot-bar-item-renderer)
m.youtube.com##ytm-browse ytm-rich-item-renderer:has(ytm-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d|1:0\d)$/))
m.youtube.com##ytm-browse ytm-item-section-renderer:has(ytm-thumbnail-overlay-time-status-renderer[data-style="SHORTS"])
m.youtube.com##ytm-search ytm-compact-video-renderer:has(ytm-thumbnail-overlay-time-status-renderer[data-style="SHORTS"])
m.youtube.com##ytm-single-column-watch-next-results-renderer ytm-video-with-context-renderer:has(ytm-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d|1:0\d)$/))
```

Here is an alternative version that sets a red background instead of hiding them, to test for false positives
```
m.youtube.com##ytm-pivot-bar-renderer div.pivot-shorts:upward(ytm-pivot-bar-item-renderer):style(background:red)
m.youtube.com##ytm-browse ytm-rich-item-renderer:has(ytm-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d|1:0\d)$/)):style(background:red)
m.youtube.com##ytm-browse ytm-item-section-renderer:has(ytm-thumbnail-overlay-time-status-renderer[data-style="SHORTS"]):style(background:red)
m.youtube.com##ytm-search ytm-compact-video-renderer:has(ytm-thumbnail-overlay-time-status-renderer[data-style="SHORTS"]):style(background:red)
m.youtube.com##ytm-single-column-watch-next-results-renderer ytm-video-with-context-renderer:has(ytm-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d|1:0\d)$/)):style(background:red)
```

I am going to test them a bit more before releasing them, any feedback is welcome!

**Comment by greggorievich** [comment]
Thanks, @xvello! I copy-pasted the latter into my uBO filters on FF Nightly Android. The Shorts button is a glorious "this goes away soon" crimson, and any videos on my home... uh, algorithm-feed, I guess, and my subscriptions were similarly highlighted. I've only tested a little bit so far, but I've not seen any false positives or false negatives as yet. 

Is there anything other than "keep an eye out and make sure things are red when they're supposed to be" I can check that would be helpful?

**Comment by xvello** [comment]
Thanks for testing it @greggorievich,

There's not really a best way than just navigating in every page and check whether something breaks. That's why having several pair of eyes is good. I'll release https://github.com/letsblockit/letsblockit/pull/232 tomorrow.

**Comment by xvello** [comment]
Hello @greggorievich, sorry for the delay here.
I just merged the fix for the channel video list, and am deploying the new release right now.

You should remove the test rules from your `my filters` tab then refresh your letsblock.it list. Don't hesitate to ping me if you think something is broken.
