### ISSUE TITLE
Restrict Google search rules to www.google.com domain

### ISSUE THREAD

**Issue by nicolaasjan** [letsblockit/letsblockit#237]
### What filter does this issue target?

search-results

### What changes should be made?

Shouldn't the filter be like `www.google.*##.g:has(a[href*=".pinterest."])`?
See [this](https://old.reddit.com/r/uBlockOrigin/comments/wqs3ae/way_to_remove_sites_from_google_web_search_but/ikt2w7z/) Reddit post.

**Comment by xvello** [comment]
Thanks for reporting this @nicolaasjan. Do you have examples of cases where false-positive append on other subdomains, or is it an added precaution?

I'll need to double-check all search uses are indeed served from the `www` subdomain, to avoid creating a regression for some users.

**Comment by nicolaasjan** [comment]
> Do you have examples of cases where false-positive happen on other subdomains, or is it an added precaution?

Unfortunately not...
I think the Reddit user I mentioned, just added it as a precaution.

> I've added `www.` to make uBlock Origin apply them only to search pages. This excludes subdomains like `drive.google.com`.

**Comment by nicolaasjan** [comment]
Thanks for the effort!
👍️

**Comment by xvello** [comment]
Thanks for the improvement suggestion! Don't hesitate to ping if you have questions or ideas.
