### ISSUE TITLE
Hide recommended videos from home page that are already in Watch Later list

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#259]
### What filter does this issue target?

youtube-recommendations

### What changes should be made?

Hide recommended videos from home page that are already in Watch Later list

**Comment by xvello** [comment]
Hello @3DWORX-SA and thanks for your ideas here and at https://github.com/letsblockit/letsblockit/issues/260! I'm replying to both here for brevity.

While cosmetic rules are pretty powerful, they are limited to what visual & semantic information is available on the elements to hide. While watched videos have some semantic information (the red progress bar) that we can match on, I cannot find any change to videos that are added to watch later (or any playlist). The action menu even allows to add them again, which makes no sense.

Unless you find something we can match on in the DOM, I don't think I can implement these two improvement ideas with uBO rules. This should be doable with [user scripts](https://greasyfork.org/en) (custom javascript executed when the page loads, that could load the user's playlists and match on it), but I'm not comfortable opening up the project outside of the uBO scope (as discussed in https://github.com/letsblockit/letsblockit/issues/47#issuecomment-1023336202) until more maintainers are on board.

Please don't hesitate to suggest other improvements, or follow-up if any visual indicator is added to such videos, making a hiding rule feasible.

**Comment by 3DWORX-SA** [comment]
Thanks Xavier - I understand the DOM issue. I find LetsBlockIt extremely useful - your work is very much appreciated.

I have looked all over for alternative ways to block videos from the YT home page on Edge for Windows that are already in a Watch Later or Play List - even looked at TamperMonkey scripts on GreasyFork but didn't find anything there.

Regards
Glenn

**Comment by xvello** [comment]
Indeed, I also searched for a userscript, but could not find any. The main issue here is that the playlist contents are not readily available, and would need to be fetched separately, either from [the public API](https://developers.google.com/youtube/v3/docs/playlistItems/list), or by downloading the playlist pages with [GM_download](https://www.tampermonkey.net/documentation.php#GM_download) and parsing them. That would create a significant delay, that one could mitigate by caching the data with [GM_setValue](https://www.tampermonkey.net/documentation.php#GM_setValue) and getValue.

I personally prefer to stay away from javascript as much as possible, but maybe someone on [r/userscripts](https://reddit.com/r/userscripts/) could give you a hand in implementing such logic.
