### ISSUE TITLE
Hide recommended videos from home page that are already in a Play List

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#260]
### What filter does this issue target?

youtube-recommendations

### What changes should be made?

Hide recommended videos from home page that are already in a Play List

**Comment by xvello** [comment]
Closing as `not-possible` for the same reasons as discussed in https://github.com/letsblockit/letsblockit/issues/259. Could be implemented with a pretty complex userscript, but definitely not a uBO rule. We can reopen these in the future if the pages change and some element property can be matched on.
