### ISSUE TITLE
youtube disable doubleclick to fullscreen

### ISSUE THREAD

**Issue by mailyspamy** [letsblockit/letsblockit#262]
### What website(s) would this filter apply to?

youtube

### What content should be blocked?

disable doubleclick to fullscreen
it is anoying on touchscreen if you want to skip 10 sec and instead of skipping it goes fullscreen
i found a solution already somewhere on internet, so it could be only added

### Did you write a custom uBlock filter already?

youtube.com##+js(aeld, dblclick)

**Comment by xvello** [comment]
Thanks a lot for your contribution @mailyspamy!

I am adding this as an option in the [youtube-cleanup](https://letsblock.it/filters/youtube-cleanup) template. It's already merged and deployed!

**Comment by mailyspamy** [comment]
Thank you for merge. It was really quick.
letsblock.it is really great idea, thank you for doing such a thing.
