### ISSUE TITLE
Hiding youtube shorts from the mini/collapsed menu

### ISSUE THREAD

**Issue by fieraoh** [letsblockit/letsblockit#265]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

at line 2:

www.youtube.com###items #endpoint[title="Shorts"]:upward(ytd-mini-guide-entry-renderer)

The shorts entry is not omitted from the mini menu, I do not know why the filter does not work exactly, maybe because the "items" id is not unique across the document.

### Did you write a uBlock filter solving this?

www.youtube.com##.ytd-mini-guide-renderer > #endpoint[title="Shorts"]

Replacing that with a direct children selector of elements with the class "ytd-mini-guide-renderer" fixes the issue

**Comment by xvello** [comment]
Hello @fieraoh and thanks for reporting this. Could you please try out the following rule, that could replace both lines 1 and 2:

```adlblock
www.youtube.com##a#endpoint[title="Shorts"]:upward(ytd-guide-entry-renderer,ytd-mini-guide-entry-renderer)
```

**Comment by fieraoh** [comment]
Hey @xvello,

This does not work as there is no such selector as element-id "a#endpoint". We could combine the two using a class-element selector, so the end result would be something like this:

www.youtube.com##a.yt-simple-endpoint[title="Shorts"]:upward(ytd-guide-entry-renderer,ytd-mini-guide-entry-renderer)

**Comment by xvello** [comment]
Ah, that means we are served different HTML, because I have these ids. Unfortunately `a.yt-simple-endpoint` matches every button on the interface, and I prefer to make the rules as specific as possible, to avoid false-positives and improve performance. Does your HTML have the `ytd-mini-guide-renderer` and `ytd-guide-renderer` elements wrapping the menu items? If so, we could go with the following two rules, that work on my end:

```adblock
www.youtube.com##ytd-guide-renderer a.yt-simple-endpoint[title="Shorts"]:upward(ytd-guide-entry-renderer)
www.youtube.com##ytd-mini-guide-renderer a.yt-simple-endpoint[title="Shorts"]:upward(ytd-mini-guide-entry-renderer)
```

**Comment by xvello** [comment]
Thanks for the quick feedback. `#items`, like `#content` is used in a lot of components across the UI, so it's not very selective. If the rule pair above work on your browser, I'll deploy an updated version tonight.

**Comment by fieraoh** [comment]
Sorry for the late reply, and, yes, they do work. Thanks for your time.

I have another question unrelated to this issue, I have originally found your solution while I was searching for a way to hide YouTube shorts, yet, I found your take on cosmetic filtering to be very creative and innovative, I also feel like myself and many others are inherently missing out on the full functionality of your project.

Could you communicate your idea with more ad block developers so they could add support for self hosted user filters?
