### ISSUE TITLE
Looking for maintainer: Twitter cleanup template

### ISSUE THREAD

**Issue by gwarser** [letsblockit/letsblockit#269]
### What website(s) would this filter apply to?

twitter.com

### What content should be blocked?

All sort of recommended stuff

### Did you write a custom uBlock filter already?

https://www.reddit.com/r/uBlockOrigin/wiki/solutions#wiki_twitter

### Additional notes

https://www.reddit.com/r/uBlockOrigin/comments/xzils7/twitter_trending_posts_an_alternative_to_ads/

**Comment by xvello** [comment]
Hello @gwarser, thanks for your suggestion!

I saw these rules in the wiki and though like you that they are a great fit for this project's scope. I am somewhat reluctant to create a `twitter-cleanup` template myself though, as I foresee it will require regular updates and I am not a twitter.com user. To make it sustainable and dependable, I would need an active twitter.com user to step up as maintainer: they would notice breakages and new stuff to hide and update the rules when needed. Would you be interested in trying out that role?

I would be happy to help with the template creation of course: [youtube-cleanup.yaml](https://github.com/letsblockit/letsblockit/blob/main/data/filters/youtube-cleanup.yaml) is a good blueprint to start from, we'll need to decide on a small number of options we can group the rules under.

**Comment by gwarser** [comment]
I'm not a Twitter user :)

**Comment by xvello** [comment]
Fair enough! I'm leaving this issue open and will try to collect a couple more before publishing a call for contributors later this year.

**Comment by JohnyP36** [comment]
> Hello @gwarser, thanks for your suggestion!
> 
> I saw these rules in the wiki and though like you that they are a great fit for this project's scope. I am somewhat reluctant to create a `twitter-cleanup` template myself though, as I foresee it will require regular updates and I am not a twitter.com user. To make it sustainable and dependable, I would need an active twitter.com user to step up as maintainer: they would notice breakages and new stuff to hide and update the rules when needed. Would you be interested in trying out that role?
> 
> I would be happy to help with the template creation of course: [youtube-cleanup.yaml](https://github.com/letsblockit/letsblockit/blob/main/data/filters/youtube-cleanup.yaml) is a good blueprint to start from, we'll need to decide on a small number of options we can group the rules under.

Although I'm not a Twitter user, I will have a look at the proposed rules and make a new template. 
Just give me some time...

**Comment by xvello** [comment]
It's been seven months without anyone stepping up, so I'll timeout and close this issue.
