### ISSUE TITLE
Youtube disable youtube tv popup

### ISSUE THREAD

**Issue by Spark-NV** [letsblockit/letsblockit#275]
### What website(s) would this filter apply to?

youtube

### What content should be blocked?

The popup in the bottom left corner that tells you about joining youtube tv.

I get these popups randomly saying stuff like "football is back! Watch football games all season long, live and cable-free with YouTube TV"

### What options should be offered?

disable the youtube tv popups

**Comment by xvello** [comment]
Closing as discussed in https://github.com/letsblockit/letsblockit/issues/274: better suited for one of the annoyances list.
