### ISSUE TITLE
Give us a way to subscribe to everything without signing up or self hosting

### ISSUE THREAD

**Issue by probonopd** [letsblockit/letsblockit#281]
Please give us a way to subscribe to everything without signing up or self hosting.

**Comment by xvello** [comment]
Hello @probonopd and thanks for opening that issue. I do think we need to discuss more about the why here, before moving forward. The scope of this project is to give a home to uBO rules that either:

- don't make a consensus in the community, making them unfit for annoyances lists from EasyList and AdGuard. Examples of these are the youtube-shorts, youtube-cleanup, google-search-cleanup or soundcloud-reposts templates
- require customization the useful, such as search-results, amazon-products, twtter-tweets-by-hashtags and several others.

When I think 100% of browser users would want a given rule, I will redirect the requests to the EasyList and AdGuard projects, as I did in https://github.com/letsblockit/letsblockit/issues/148 and https://github.com/letsblockit/letsblockit/issues/129. This means that the project is bound to eventually add a template or a default option with which you will disagree. This is why customization is at the core of this project.

Could you please tell me:

- how such a "every rule" list would work, when more than half of the templates are useless without settings?
- why creating an account on the official instance is not OK with you? I went out of my way to make the project as privacy-forward as possible, as described in the [privacy page](https://letsblock.it/help/privacy)

Thanks!

**Comment by xvello** [comment]
Another way to use the template corpus is to use [the render CLI](https://github.com/letsblockit/letsblockit/tree/main/cmd/render), to build a list that you'll upload somewhere of your choosing. That was the initial way I used the search-results template, before I decided to build the server. 

I could create an example repository using github actions to publish it daily, if that's something that could work with you. It is still currently rough around the edges (you need to check the template sources to get the parameter names, but the CLI could be extended to list all templates and all parameters for a template.

**Comment by probonopd** [comment]
Well, I am trying to ship my operating system preconfigured with a list that blocks every ad that anyone ever has defined as being an ad. The "mainstream" lists do not block everything.

**Comment by xvello** [comment]
Yes, what you could do is create an account on a project's email address, select the templates that look useful to your audience, then get the list download URL to add it to your default configuration.

Knowing the download URL does not allow to modify the list, so it's safe to share with others.

**Comment by xvello** [comment]
Hello @probonopd, sorry for the delay in replying.

One way to remove account creation would be to encode template parameters in the download URL, but this is not something I am willing to implement at the moment: 

As the project is still young and exploring its problem space, we are iterating a lot. This means [merging templates](https://github.com/letsblockit/letsblockit/blob/main/src/db/migrations/0003_merge-youtube-streams-chat.up.sql), changing [the meaning of options](https://github.com/letsblockit/letsblockit/blob/main/src/db/migrations/0006_google-search-cleanup-rich-content.up.sql) or [default values](https://github.com/letsblockit/letsblockit/blob/main/src/db/migrations/0004_duckduckgo_lite.up.sql). Storing state on the server allows us to handle these breaking configuration changes with database migrations without impacting users. I don't think we're mature enough to renounce to this flexibility.

As for providing a non configurable opinionated rule list, this is opposite to this project's scope. Please don't take this as me stating that your need is not valid, it is me being protective about the project's scope to keep it sustainable.

The template corpus is published under the Apache 2 license and anyone can reuse it, either using [the render CLI](https://github.com/letsblockit/letsblockit/tree/main/cmd/render) or custom tooling, like this project reuses the work of [quenhus/uBlock-Origin-dev-filter](https://github.com/quenhus/uBlock-Origin-dev-filter).

**Comment by probonopd** [comment]
Thanks @xvello. I think encoding parameters in the URL would be the way to go but  I understand that the project has limited resources. Anyway, thanks for the pointers and keep up the good work!
