### ISSUE TITLE
Filter suggestion (YT): Hide particular channel from search results

### ISSUE THREAD

**Issue by Leseratte10** [letsblockit/letsblockit#295]
### What website(s) would this filter apply to?

YouTube search results

### What content should be blocked?

I'd like to have a filter to hide all videos from a given channel / user. The YouTube search isn't that great, and every now and then, depending on the topic, one or two crap channels with a ton of unnecessary spam videos each manage to show up in my search results for whatever reason and I'll always have to try to exclude them with `-ChannelName` in the search (which sometimes works and sometimes doesnt).

I'd like a way to be like "Hey, never show me any videos uploaded by the channel with this particular channel URL anywhere". 

I tried clicking "Not interested" or "Do not suggest videos from this channel" but that only seems to help to remove these videos from the home page, not from search results. I did not find a YouTube-native way to hide them from search results (or, even better, from everywhere).

I found the existing patch [Hide Youtube videos by title](https://letsblock.it/filters/youtube-video-title) but that can only filter by title, not by uploader. Also I think filtering the uploader URL is better than the displayed name because the displayed name, to my knowledge, may not be unique.

### What options should be offered?

The list of channels to block should be customizable. Other than that I don't think it needs much customization.

### Did you write a custom uBlock filter already?

No, I don't; I've never written a uBlock filter before sadly. 
I guess it would need to check the URL the uploader's name points to, and if that URL is on a blacklist it would remove that whole video element from the search results?

**Comment by xvello** [comment]
Heya @Leseratte10, the new template is deploying right now, I hope it works great for your need!
