### ISSUE TITLE
Hide Youtube videos you already watched not working

### ISSUE THREAD

**Issue by FahadBinHussain** [letsblockit/letsblockit#306]
### What filter does this issue target?

Hide Youtube videos you already watched

### What changes should be made?

To simply put, the filter is not working on "https://www.youtube.com/c/[CHANNEL]/videos" page.

And only this option is checked.

![image](https://user-images.githubusercontent.com/75292632/201518250-d871c55d-f0fb-4c1a-800b-fb676763828a.png)

Edit: It works when the 2nd option is checked like this.

![image](https://user-images.githubusercontent.com/75292632/201518495-c802c427-f324-4b66-b509-9fa0348c0431.png)

**Comment by krystian3w** [comment]
So on specific channel no longer exist tag:

```html
<ytd-grid-video-renderer> blah blah blah </ytd-grid-video-renderer>
```

**Comment by xvello** [comment]
Hello @FahadBinHussain and @krystian3w, thanks for reporting this! I'm a bit swamped at the moment, but I'll take a look at it this month. Sorry for the delay.

**Comment by xvello** [comment]
Heya, thanks for your patience. This is fixed in today's deploy.

The issue is that the homepage rule was not specific enough, and matching the channel page too. This is why I could not reproduce this issue.
