### ISSUE TITLE
add support for Brave search

### ISSUE THREAD

**Issue by textOper** [letsblockit/letsblockit#322]
### What filter does this issue target?

https://letsblock.it/filters/search-results

### What changes should be made?

add support for new search engine: [Brave search](https://search.brave.com/)

**Comment by xvello** [comment]
Hello @textOper, thanks for your suggestion. I don't have much time to dedicate to that right now, but I'd be happy to review a PR to [the template](https://github.com/letsblockit/letsblockit/blob/main/data/filters/search-results.yaml). uBlock-Origin-dev-filter already has [a rule for text results](https://github.com/quenhus/uBlock-Origin-dev-filter/blob/b1837139ab0669a9b3cf90c961c408f6748cbbea/src/generate.py#L41) that we could reuse, but it would be great to also filter out image results, for parity with other search engines.

**Comment by xvello** [comment]
Brave is now available as an option at https://letsblock.it/filters/search-results , feel free to give us feedback if something could be improved!
