### ISSUE TITLE
Allow custom time filter

### ISSUE THREAD

**Issue by bennieboi20** [letsblockit/letsblockit#324]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

It would be good if we could manually select a threshold for the length of the video so that we can try to lower the amount of false positives. 
For example https://www.youtube.com/watch?v=H4HAuU13eMU is under 60 seconds however it is not a Youtube short.
It would be nice if we could manually adjust it like we can for https://letsblock.it/filters/youtube-video-title

Youtube no longer automatically adds "shorts" to the end of the video and as such just a name filter no longer works 
For example: https://www.youtube.com/shorts/U0BBf2Pi6pg

However since Youtube uses the "shorts" subdomain is it possible to have the filter look at the link of the video and hide them that way?

Thanks!

**Comment by BPower0036** [comment]
For your second and last paragraph, see Pull Request https://github.com/letsblockit/letsblockit/pull/317.

**Comment by bennieboi20** [comment]
> For your second and last paragraph, see Pull Request #317.

I added your two new rules you wrote in that pull request however they dont seem to work or did i do something wrong?

**Comment by BPower0036** [comment]
```
www.youtube.com##ytd-browse ytd-grid-video-renderer:has(span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"])
www.youtube.com##ytd-browse ytd-rich-item-renderer:has(span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"])
www.youtube.com##ytd-search ytd-video-renderer:has(span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"])
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"])
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-shelf-renderer:has(span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"])
www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer span.ytd-thumbnail-overlay-time-status-renderer[aria-label="Shorts"]:upward(ytd-item-section-renderer)
```
is replaced by:
```
www.youtube.com##ytd-browse[page-subtype="home"] ytd-rich-item-renderer:has(.ytd-thumbnail[href^="/shorts/"])
www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-grid-video-renderer:has(.ytd-thumbnail[href^="/shorts/"])
www.youtube.com##ytd-search ytd-video-renderer:has(.ytd-thumbnail[href^="/shorts/"])
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(.ytd-thumbnail[href^="/shorts/"])
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-shelf-renderer:has(.ytd-thumbnail[href^="/shorts/"])
www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer .ytd-thumbnail[href^="/shorts/"]:upward(ytd-item-section-renderer)
```
They only work at the homepage, subscription-page, search-page, and watch-next column.

**Comment by xvello** [comment]
Hello @bennieboi20, the outdated rules filtering by duration have been removed, you'll get the fix within 24 hours, or earlier if you [refresh your list](https://letsblock.it/help/refresh-list) to grab it!
