### ISSUE TITLE
Hide Youtube videos by title should look for other separators if possible

### ISSUE THREAD

**Issue by squeak9** [letsblockit/letsblockit#347]
### What filter does this issue target?

https://letsblock.it/filters/youtube-video-title

### What changes should be made?

If you wanna block `lofi` or `hip hop` for example then titles like these won't get filtered:
```
[Lofi Hip hop]
(Lofi Hip hop)
【Lofi Hip hop】
『Lofi Hip hop』
{Lofi Hip hop}
「Lofi Hip hop」
```
These separators are real common as in titles for showing the topic of the video which makes them a valuable target for filtering.

I can understand that this might be a huge rabbit hole, maybe this should be an optional checkbox? Also this might be real tricky to filter but it would really make the filter way better! Entering all variations of `[Lofi` and `lofi」` would be a huge hassle.

EDIT: Maybe an optional thing that doesn't rely on spaces based matching would be easiest?

### Additional notes

Ideally this would also factor in punctuation but that's a whole other rabbit hole:

```
Lofi Hip hop!
Lofi Hip hop.
Lofi Hip hop,
Lofi Hip hop?
Lofi Hip hop！
Lofi×Hip hop
Lofi・Hip・hop
Lofi Hip hop。
```
The last ones are more common in Japanese titles but not exclusive to them.
Most titles don't use punctuation for their topics so might not be worth it to filter these.

**Comment by squeak9** [comment]
So maybe there could be optional separate "agressive mode" word list for very specific or trademarked stuff like the title of a movie that definitely won't be combined with other words like `lord of the rings`?

Now I know the `*` trick at least and can use that for my needs, thanks for that.

**Comment by JohnyP36** [comment]
@squeak9 As xvello proposed in https://github.com/letsblockit/letsblockit/pull/348#issuecomment-1421038583 using regex is better, because that won't give false-positives and will solve this problem to. 

So for the YouTube homepage, use
```yaml
www.youtube.com##ytd-browse ytd-rich-item-renderer:has(#video-title-link[title]:has-text(/\blofi\b/i))
```
##### warning: only replace `lofi` with other words, not the first b.

**Comment by xvello** [comment]
Hello @squeak9, thanks for reporting this!

[Johny's PR](https://github.com/letsblockit/letsblockit/pull/348) has just been deployed, your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it.

I'm still leaving the issue open for now, as the template will work fine with bare words, but will fail if the user inputs some special characters. I'll follow-up on this later. In the meantime, make sure you remove template params with punctuation if you have any.

**Comment by squeak9** [comment]
Thanks for the fixes!

**Comment by xvello** [comment]
Closing in favour of https://github.com/letsblockit/letsblockit/pull/352 for the support of regexp params. The initial issue has been fixed already.
