### ISSUE TITLE
Hide archived live streams from YouTube subscription box

### ISSUE THREAD

**Issue by NathanW36** [letsblockit/letsblockit#375]
### What filter does this issue target?

https://letsblock.it/filters/youtube-upcoming-videos

### What changes should be made?

Add an option to hide live streams that have finished an now show as an archived video in your subscription box, with the text "Streamed X hours ago" underneath 

### Did you write a uBlock filter solving this?

I'm able to target these videos with the following code, but I can't get it to hide videos which contain it:

.ytd-grid-video-renderer.style-scope:has-text(Streamed)

**Comment by JohnyP36** [comment]
The rule `##ytd-grid-video-renderer:has(#metadata-line:has-text(Streamed))` should work. 

I tested it on `https://www.youtube.com/channel/UC4R8DWoMoI7CAwX8_LjQHig`

**Comment by xvello** [comment]
Heya @NathanW36, thanks for suggesting this addition, and thanks @JohnyP36 for writing this rule!

As we discussed in https://github.com/letsblockit/letsblockit/issues/349, I have reservations against adding templates that match on display strings, as that rule does not work in French for example. After looking at the DOM, there's unfortunately no semantic element that allows such filtering though :/

**Comment by xvello** [comment]
I'm gonna close this one, as it's currently not within the reach of our limitations. But I'd be happy to re-evaluate if we find a rule that works without matching on display text.

**Comment by JohnyP36** [comment]
> I'm gonna close this one, as it's currently not within the reach of our limitations. But I'd be happy to re-evaluate if we find a rule that works without matching on display text.

That's fine, as until now this is not possible.
