### ISSUE TITLE
Updating youtube-shorts filter to block new shorts window on normal videos on desktop

### ISSUE THREAD

**Issue by SiggyPony** [letsblockit/letsblockit#389]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

Youtube is now showing shorts on the left basically all normal videos.
I think we should add a new line to the youtube shorts filter to account for this.

![image](https://user-images.githubusercontent.com/11322269/230712863-c06e2280-9fec-4012-8aab-d1b1a0f17afc.png)

I hope this helps :) I just accidentally got lost in shorts for 30minutes without even realizing

### Did you write a uBlock filter solving this?

www.youtube.com##ytd-reel-shelf-renderer

### Additional notes

The new line is almost identical to one that already exists for mobile see,

m.youtube.com##ytm-reel-shelf-renderer

**Comment by xvello** [comment]
Thanks a lot @SiggyPony:

- could you please test this more selective rule and comfirm that it works?

```adblock
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-reel-shelf-renderer
```

- I'd like to give you attribution on the commit adding that rule, could you please give me the `@users.noreply.github.com` email that is shown in https://github.com/settings/emails, so that I can add it as co-author?

**Comment by SiggyPony** [comment]
Hey,  yes that more specific rule also works.
If you want to give some attribution I think its,  11322269+SiggyPony@users.noreply.github.com   
Took a bit to figure out, I don't generally use github 😅

**Comment by xvello** [comment]
Cool! It's been merged and deployed, you can remove the custom ruke and [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it!
