### ISSUE TITLE
Remove Google search Questions & Answers in right hand pane

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#394]
### What filter does this issue target?

Any Google search result page

### What changes should be made?

Can the **Questions & Answers** section in the right hand pane of the Google search results page be removed? Some of these are so dumb as to be useless and annoying.

### Did you write a uBlock filter solving this?

No

**Comment by JohnyP36** [comment]
@3DWORX-SA could you provide a screenshot, so I know what you mean. 
For me, I only see this if I search a question 

<details><summary>Screenshot</summary>

![afbeelding](https://user-images.githubusercontent.com/81161435/231991549-e1a0577c-cd6b-4317-b6d6-6d85e0b27804.png)

</details>

Did you also check the [`Google Search: interface cleanups` template](https://letsblock.it/filters/google-search-cleanup)?
It has two rules for your request *I think*: 
```
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(div.related-question-pair)
www.google.*###kp-wp-tab-overview > div:has(div.related-question-pair)
```
Maybe they work for your problem.

**Comment by 3DWORX-SA** [comment]
This happened when searching for "SAPS Midrand"
![image](https://user-images.githubusercontent.com/32925097/232006944-cbb3e0bd-fa21-41ac-82f1-2ffa9fbf86b3.png)

**Comment by JohnyP36** [comment]
@3DWORX-SA Thank you for your issues. I opened a PR regarding this. See #396

**Comment by xvello** [comment]
Thanks @3DWORX-SA for the idea and @JohnyP36 for the PR!
It's available on https://letsblock.it/filters/google-search-cleanup now
