### ISSUE TITLE
Remove Google search Reviews in right hand pane

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#395]
### What website(s) would this filter apply to?

Any Google search result page

### What content should be blocked?

Can the **Reviews** section in the right hand pane of the Google search results page be removed? It is meaningless in most search results.

### Did you write a custom uBlock filter already?

No

**Comment by xvello** [comment]
Thanks @3DWORX-SA for the idea and @JohnyP36 for the PR!
It's available on https://letsblock.it/filters/google-search-cleanup now

**Comment by 3DWORX-SA** [comment]
Hi Xavier - Thanks for the very prompt update!
However, I have forced an update in uBlock Origin and restarted Edge but still get "Questions & answers", "Reviews from the web" and "Reviews" in the right hand column of Google search results when searching for the search term "saps midrand".
Do you see this too? Or am I testing a bit too soon? I did see the Github commit.

***@***.***
Regards
Glenn

**Comment by JohnyP36** [comment]
@3DWORX-SA The rules work on my side. Can you manually verify if the rules work by adding them to uBlock?

```
www.google.*###rhs div[jsdata]:has([class*="wholepage-card"]):nth-of-type(5)
www.google.*###rhs div[jsdata]:has([class*="wholepage-card"]):nth-of-type(8)
```

**Comment by 3DWORX-SA** [comment]
Hi - I added them to the "My Filters" tab in uBlock, applied changes and restarted Edge, but a search for "saps midrand" still shows "Questions & answers", "Reviews from the web" and "Reviews" in the right hand column of Google search results.

Is there anything else I can provide or check?

**Comment by 3DWORX-SA** [comment]
Hi - I added them to the "My Filters" tab in uBlock, applied changes and restarted Edge, but a search for "saps midrand" still shows "Questions & answers", "Reviews from the web" and "Reviews" in the right hand column of Google search results.

Is there anything else I can provide or check?

***@***.***

**Comment by xvello** [comment]
I can indeed reproduce with the same web search. The kind of items on the sidebar is not consistent across searches, so the `:nth-of-type` selector won't work great here.

@JohnyP36, these items seem to have obfuscated `data-hveid` attributes, we could hope they are stable and filter on that?

For example for reviews:
```adblock
www.google.*###rhs #kp-wp-tab-overview div[data-hveid="CGAQAA"]
```

**Comment by xvello** [comment]
(btw, to get adblock syntax highlighting in your code blocks, just start them with \`\`\`adblock instead of just \`\`\`)

**Comment by JohnyP36** [comment]
> I can indeed reproduce with the same web search. The kind of items on the sidebar is not consistent across searches, so the `:nth-of-type` selector won't work great here. @JohnyP36, these items seem to have obfuscated `data-hveid` attributes, we could hope they are stable and filter on that?
> 
> For example for reviews:
> 
> ```
> www.google.*###rhs #kp-wp-tab-overview div[data-hveid="CGAQAA"]
> ```

Your example is on my side for the "Q&A section"

So, I would suggest
```adblock
www.google.*###rhs #kp-wp-tab-overview div[data-attrid*="review"]
www.google.*###rhs #kp-wp-tab-overview div[data-attrid*="third_party_aggregator_ratings"]
www.google.*###rhs #kp-wp-tab-overview div[data-attrid*="qa"]
```

The first and second are for reviews and the last for the question section.

These rules seem to work properly everywhere. I searched for `Naicom systems`, `saps midrand` and `ikea city stockholm`

**Comment by xvello** [comment]
The fix is deployed and available after you [manually refresh your list](https://letsblock.it/help/refresh-list). These options are not on by default, so you need to enable them in https://letsblock.it/filters/google-search-cleanup first.

Looks great now (I'm using the test mode to set a red border instead of hiding)!
![image](https://user-images.githubusercontent.com/6241083/232040700-06451862-6c48-45ed-9879-a18348ea0c0a.png) 
![image](https://user-images.githubusercontent.com/6241083/232040853-b8810edb-e98c-40e7-9b5c-3e84542d357b.png)

**Comment by 3DWORX-SA** [comment]
Thank you and well done – it works! Very much appreciated folks 😊
Until Google throws another surprise our way… Keep well!
