### ISSUE TITLE
disable swipe on youtube chanel page and disable PIP mode with swipe down

### ISSUE THREAD

**Issue by mailyspamy** [letsblockit/letsblockit#400]
### What website(s) would this filter apply to?

youtube

### What content should be blocked?

it is anoying if you want to start video on channel, but because of light swipe you change the tab to shorts. The same iif you want to scroll down with swipe and youtube switch to picture in picture mode.
I got an answer with solution on ublock reddit so you can add it if you want.
https://www.reddit.com/r/uBlockOrigin/comments/115f6rz/disable_some_touch_functionality_on_a_full/

### Did you write a custom uBlock filter already?

```adblock
www.youtube.com##+js(aeld, /^pan(start|move|end)$/)
```

**Comment by JohnyP36** [comment]
Thanks for the idea.  @xvello has to decide if we could implement this rule in one of the existing templates (https://letsblock.it/filters/tag/youtube).

**Comment by xvello** [comment]
Thanks @mailyspamy!

I feel like it fits within the scope of `youtube-cleanup`, alongside the `no-fullscreen-on-dblclick` option. It is now available at https://letsblock.it/filters/youtube-cleanup

**Comment by mailyspamy** [comment]
Thanks xvello. Hope it will be usable also for another people.
