### ISSUE TITLE
Include Trending Page in blocking Youtube Shorts

### ISSUE THREAD

**Issue by Tumpo** [letsblockit/letsblockit#411]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

Can trending pages (trending itself, gaming/music/etc trending under explore) be included in this blocking aswell?

Thanks!

**Comment by Tumpo** [comment]
Yes the first one. Did not work for me. On /trending nor at https://www.youtube.com/gaming/trending.

**Comment by xvello** [comment]
Heya @Tumpo,

A new rule has just been deployed, can you please test it? Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it.

If there's still shorts showing up, can you please post a screenshot AND a url? There are several designs shown in different countries, so we might not be able to reproduce what you're seeing.

**Comment by Tumpo** [comment]
It is working now.

**Comment by xvello** [comment]
Thanks! Closing the issue then.
