### ISSUE TITLE
youtube-recommendations: add rules for mobile version

### ISSUE THREAD

**Issue by chedani** [letsblockit/letsblockit#422]
### What filter does this issue target?

YouTube: hide video recommendations

### What changes should be made?

The current set of filters doesn't remove home page videos and related videos. You could use the following links to force youtube mobile site (and back to desktop site) to debug in the computer.

Youtube Mobile:
https://m.youtube.com/?persist_app=1&app=m

Youtube Desktop:
https://www.youtube.com/?persist_app=1&app=desktop

### Did you write a uBlock filter solving this?

This is my first time writing filters. So there maybe a better way, but here is what I have. I have tested this on my phone.

m.youtube.com##div[tab-identifier^="FEwhat_to_watch"]
m.youtube.com##ytm-item-section-renderer[data-content-type="related"]

### Additional notes

Thank you for creating the filters! I am trying to limit my time spent on Youtube mindlessly.

**Comment by xvello** [comment]
Heya @chedani, thanks for the idea and the rules!

The second rule looks good (although I'm gonna make it a bit more specific to avoid side effects), but I don't understand what the first rule is designed to match. Could you please post a URL and a screenshot?

**Comment by chedani** [comment]
Thank you for showing me a better way to write the filters. I tested them and they still work well. Can you add the rules please?
