### ISSUE TITLE
YouTube: filter out videos by channel  - for mobile version

### ISSUE THREAD

**Issue by leo1115** [letsblockit/letsblockit#431]
### What filter does this issue target?

https://letsblock.it/filters/youtube-channel

### What changes should be made?

support for channel filtering on m.youtube.com

### Did you write a uBlock filter solving this?

to block @MikeBoyd from search results on m.youtube.com
```
m.youtube.com##ytm-search ytm-video-with-context-renderer:has(a[href$="@MikeBoyd"])
m.youtube.com##ytm-search ytm-compact-channel-renderer:has(a[href$="@MikeBoyd"])
```
this works perfectly 

### Additional notes

to block @MikeBoyd from homepage 

`m.youtube.com##ytm-browse ytm-rich-item-renderer:has(a[href$="@MikeBoyd"])`

does not seem to be working for me. if someone can improve the homepage rule it would be great.

**Comment by JohnyP36** [comment]
For the normal youtube site are the rule 

```adblock
www.youtube.com##ytd-browse[page-subtype="home"] ytd-rich-item-renderer:has(a[href$="{{ . }}"])
www.youtube.com##ytd-search ytd-video-renderer:has(a[href$="{{ . }}"])
www.youtube.com##ytd-search ytd-channel-renderer:has(a[href$="{{ . }}"])
```

can you test if those rule **but without the `www`** also work for the mobile version?

**Comment by leo1115** [comment]
> can you test if those rule but without the www also work for the mobile version?

no these dont work with m.youtube.com.

but i was able to modify the last 2 rules. these work with m.youtube.com:
```
m.youtube.com##ytm-search ytm-video-with-context-renderer:has(a[href$="{{ . }}"])
m.youtube.com##ytm-search ytm-compact-channel-renderer:has(a[href$="{{ . }}"])
```

**Comment by JohnyP36** [comment]
How does the rule starting with `m.` not work? 
What is the url displayed on your mobile?

**Comment by leo1115** [comment]
apologies. did some more testing & `m.` rule is working as well. i perhaps accidently switched to the desktop version yesterday. 
```
m.youtube.com##ytm-browse ytm-rich-item-renderer:has(a[href$="{{ . }}"])
m.youtube.com##ytm-search ytm-video-with-context-renderer:has(a[href$="{{ . }}"])
m.youtube.com##ytm-search ytm-compact-channel-renderer:has(a[href$="{{ . }}"])
```
these are working well.
