### ISSUE TITLE
"Hide already watched" filter not working on new YouTube layout

### ISSUE THREAD

**Issue by yokoffing** [letsblockit/letsblockit#449]
### Describe the bug

These don't seem to work anymore
```
! Hide already watched YouTube videos
www.youtube.com##ytd-browse[page-subtype="home"] ytd-rich-item-renderer:has(ytd-thumbnail-overlay-resume-playback-renderer)
www.youtube.com##ytd-browse[page-subtype="channels"] ytd-rich-item-renderer:has(ytd-thumbnail-overlay-resume-playback-renderer)
www.youtube.com##ytd-browse[page-subtype="channels"] ytd-grid-video-renderer:has(ytd-thumbnail-overlay-resume-playback-renderer)
www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-grid-video-renderer:has(ytd-thumbnail-overlay-resume-playback-renderer)
www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer ytd-thumbnail-overlay-resume-playback-renderer:upward(ytd-item-section-renderer)
www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-compact-video-renderer:has(ytd-thumbnail-overlay-resume-playback-renderer)
```

### Your browser and device

Firefox

### Reproduction steps

```bash
1. Watch youtube videos
2. Go to Subscriptions page
```

### Expected behavior

Hide all watched and mostly watched videos.

![already watched](https://github.com/letsblockit/letsblockit/assets/11689349/71fb001c-20cc-4cfd-a0ab-4e540dab209e)

**Comment by xvello** [comment]
Hello @yokoffing, thanks for reporting this! We'll have a look at it shortly.

**Comment by xvello** [comment]
That's a known issue with their new shitty layout: thumbnails are now in fixed rows, so any removed video (not just shorts, but watched, filtered by channel...) leaves a gap.

The two last rules in https://github.com/orgs/letsblockit/discussions/450 inject custom CSS that work around this. We'll need to decide whether we want to maintain this CSS hack into our rules corpus.

**Comment by xvello** [comment]
Heya @yokoffing , could you please try the following rule for the subscription page?

```adblock
www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-thumbnail-overlay-resume-playback-renderer:upward(ytd-grid-video-renderer,ytd-video-renderer,ytd-rich-item-renderer)
```

**Comment by xvello** [comment]
My bad, I was meaning to link to https://github.com/letsblockit/letsblockit/issues/452

```adblock
youtube.com##ytd-rich-grid-row, #contents.ytd-rich-grid-row:style(display:contents !important;)
youtube.com##ytd-rich-grid-renderer:style(--ytd-rich-grid-items-per-row: 4 !important;)
```

you can change the second line to set the number of items per row

**Comment by xvello** [comment]
Hey @yokoffing,

The fix has just been deployed! Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it! Don't forget to remove the manually added rules.

I'll audit the other youtube templates and update them too. Thanks a lot for reporting this!

**Comment by yokoffing** [comment]
```
youtube.com##ytd-rich-grid-row, #contents.ytd-rich-grid-row:style(display:contents !important;)
youtube.com##ytd-rich-grid-renderer:style(--ytd-rich-grid-items-per-row: 4 !important;)
```

These work for me!

> you can change the second line to set the number of items per row

4 seems optimal for desktop use; 5 is okay if I maximize my window

**Comment by xvello** [comment]
Yep, you can only keep the first one to force thumbnails to correctly flow, and the number of thumbnails per row will automatically be adjusted. The second rule forces a value. If I create a template for these rules, I'll leave the second disabled by default

**Comment by yokoffing** [comment]
@xvello thanks for the extra info
