### ISSUE TITLE
Youtube shorts June 2023

### ISSUE THREAD

**Issue by huoltomies** [letsblockit/letsblockit#452]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

youtube.com##:xpath(//ytd-rich-item-renderer[descendant::span[contains(@aria-label,"Shorts")]])

!This part removes the "New Row" object. kind of like removing the new paragraph in word editors.

youtube.com##ytd-rich-grid-row, #contents.ytd-rich-grid-row:style(display:contents !important;)

!This part limits the number of videos per row. go ahead and play with the number.

youtube.com##ytd-rich-grid-renderer:style(--ytd-rich-grid-items-per-row: 6 !important;)

### Additional notes

https://www.reddit.com/r/uBlockOrigin/comments/143mdqv/code_to_block_youtube_shorts_june_2023/

**Comment by xvello** [comment]
Hello @huoltomies,

The rules at https://letsblock.it/filters/youtube-shorts have been updated recently, so I'm a bit septic about these rules being necessary. Could you please make sure you use the latest version and then post screenshots of the parts where they don't properly filter out shorts?

Thanks a lot!

**Comment by huoltomies** [comment]
![New Bitmap image](https://github.com/letsblockit/letsblockit/assets/109385371/899c92dd-a61d-4c41-9663-fb76b7c51572)

**Comment by huoltomies** [comment]
They started pushing the new layout and shorts appeared again..

**Comment by xvello** [comment]
Heya @huoltomies, sorry for the late reply.

It seems like none of our team members is (for now) served the same layout as you. Could you please post a DOM dump for the element to hide:

- open the inspector panel (right click > inspect)
- find a shorts item, select its `ytd-rich-item-renderer` element (it should be highlighted in the page
- right-click and chose "Copy outer HTML"
- paste that into a code block in a comment here (put ``` on its own line, before and after the DM dump contents

Thanks for your help!

**Comment by xvello** [comment]
Hello! I'm closing this one due to inactivity, feel free to re-open if the recent updates to the template are not enough to address the layout you are seeing. In that case, please provide the debug info requested in the comment above.
