### ISSUE TITLE
search-results: Stopped working on DuckDuckGo

### ISSUE THREAD

**Issue by nicolaasjan** [letsblockit/letsblockit#473]
### What filter does this issue target?

Search engines: filter out results by website

### What changes should be made?

This filter does not work any more on DuckDuckGo (uBO `1.50.1b3`):
```
duckduckgo.com##a[data-testid="result-title-a"][href*=".realmicentral."]:upward(.nrn-react-div)
duckduckgo.com##.tile-wrap a[href*=".realmicentral."]:upward(.tile)
```
![screenshot1](https://github.com/letsblockit/letsblockit/assets/14093220/d31bda12-1505-4563-afbd-ac5f58d78b5b)

Google filter works well:

```
www.google.*##.g:has(a[href*=".realmicentral."])
www.google.*##a[href*=".realmicentral."]:upward(1)
```

![screenshot2](https://github.com/letsblockit/letsblockit/assets/14093220/e866d931-08a8-494a-bdac-f2c7d7834d2f)

**Comment by xvello** [comment]
Thanks for the report @nicolaasjan, we'll look into this shortly!

**Comment by krystian3w** [comment]
In Firefox this can be ExtendedCSS/Procedural filtering regression.

**Comment by krystian3w** [comment]
To tests in stable 1.50.0:

```adb
uckduckgo.com##a[href*=".realmicentral."]:upward(.react-results--main > li)
```

**Comment by xvello** [comment]
I can indeed reproduce the issue with uBO 1.50. They changed the page markup, but the good news is that the new markup has enough semantic information to build new rules.

**Comment by nicolaasjan** [comment]
> To tests in stable 1.50.0:
> 
> ```
> duckduckgo.com##a[href*=".realmicentral."]:upward(.react-results--main > li)
> ```

This works in `1.50.1b4` as well. 🙂

**Comment by krystian3w** [comment]
So good.

*My problem with filtering manifests itself in the fact that the column headers in Wordpress WooCommerce do not want to hide in the release 1.50.1b1-1.50.1b3 (4 I have not tested), hence the difficulty in presenting this in the demo as such 60 Minutes has only 17 products and I can not reproduce the error there with not hiding when almost every product has the "tag" field filled in.*

*In part, I'm hoping the problem will go away when Moz://a allows for all `:has()` in CSS in a year or so.*

*Worst of all, there are few changes in the code that can be blamed for procedural filtering crashing in the beta release.*

**Comment by JohnyP36** [comment]
> So good.
> 
> _My problem with filtering manifests itself in the fact that the column headers in Wordpress WooCommerce do not want to hide in the release 1.50.1b1-1.50.1b3 (4 I have not tested), hence the difficulty in presenting this in the demo as such 60 minutes demo shops has only 17 products and I can not reproduce the error there with not hiding when almost every product has the "tag" field filled in._
> 
> _In part, I'm hoping the problem will go away when Moz://a allows for all `:has()` in CSS in a year or so._
> 
> _Worst of all, there are few changes in the code that can be blamed for procedural filtering crashing in the beta release._

@krystian3w I do not completely understand what this has to do with the template rules not working. It seems you blame Firefox and/or uBlock code, but xvello said in https://github.com/letsblockit/letsblockit/issues/473#issuecomment-1599996624 that he (or we/I) can make a new rule as the site has changed their code.

**Comment by xvello** [comment]
Heya folks,

The fix has just been deployed! Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it!

Sorry for the delay, free time is a bit short this month (and probably the upcoming month too). Also, my pronouns are they/them, please use these pronouns when referring to me.

**Comment by krystian3w** [comment]
But I'm really spoiled by the procedural column filtering in the WooCoomerce store, and only going back to stable uBo helps.

I still had the old DuckDuckGo site drive engine back in the day, so I would not delete the rules forever but mark them as aged and do the deletion around December 2023.

**Comment by xvello** [comment]
Arf true, I always do that with the google website (they are so fond of month-long rollout) but didn't think that DDG would also do that. Could you please ping me if you see the old layout again?
