### ISSUE TITLE
Youtube : Filter out a channel by date

### ISSUE THREAD

**Issue by AruthaC** [letsblockit/letsblockit#474]
### What website(s) would this filter apply to?

youtube.com

### What content should be blocked?

Hey
The filter I'm thinking of would filter out the videos from a channel older than a certain timespan (older than 2 weeks, older than 1 year....)
The Hide feature is bugged on youtube(videos keep reappearing), this option would make up for it, without hiding the newest videos from a channel, and without hiding old videos when we subscribe to a new channel

### What options should be offered?

For each channel, we should be able to customise a timespan

### Did you write a custom uBlock filter already?

Sadly not, I tried to mirror this script : https://letsblock.it/filters/youtube-upcoming-videos but I don't know the variables names

**Comment by AruthaC** [comment]
To add some exemple : 
Let's say I subscribed to 3 channel A B and C
I'm up to date on channel A, so in my subscription tab, I would like to only see what A published in the last two weeks to be sure not to miss a thing
I'm catching up with B and am currently 1 year away from the present day, I'd like to see only what B published in let's say the last 54 weeks
And I haven't started watching C yet so nothing from C should be filtered out

**Comment by xvello** [comment]
Hello @AruthaC, thanks for using the project and suggesting improvements!

A similar idea has been discussed in https://github.com/letsblockit/letsblockit/issues/349, but implementing it through this project would be way too clunky and brittle: the YouTube web frontend does not expose the video age and I refuse to match on display strings, as a significant portion of our users are international.

I feel like your workflow would be better served by alternative frontends such as [NewPipe](https://github.com/TeamNewPipe/NewPipe) than by customizing the official frontend.

**Comment by AruthaC** [comment]
Hey
Thanks for your answer
Sorry, I hadn't seen issue 349
I'll check NewPipe, thanks for the suggestion
Have a nice day :)
