### ISSUE TITLE
Fandom.com bloat filters

### ISSUE THREAD

**Issue by lightbulbmeow** [letsblockit/letsblockit#490]
### What website(s) would this filter apply to?

fandom.com

### What content should be blocked?

Fandom has bunch of bloat to their website which make it extremely annoying to navigate, most notably the bright yellow sidebar and the "wikia surveys" that pop up. Most people who visit Fandom just want to read specific information about a particular show/video game.

### What options should be offered?

Ability to block the following elements:
* Yellow sidebar on the left
* The "wikia bar" on the bottom-right corner that follows you as you scroll down the page
* "Fan Feed" and Fandom footer at the very bottom of the page
* The right sidebar with the "Popular pages"
* The tooltip that pops up when you try to highlight text
* "Explore" tab on the header bar
* "Top Trending Searches" when you open search
* Edit buttons on the page

### Did you write a custom uBlock filter already?

```
! Yellow sidebar
fandom.com##.global-navigation
fandom.com##.main-container:style(margin-left: auto !important; margin-right !important: auto; width: 100% !important)
fandom.com##.fandom-sticky-header:style(left: 0 !important)
fandom.com##.search-modal::before:style(left: 0 !important)

! "Wikia bar" on the bottom-right corner
fandom.com###WikiaBar

! "Fan feed" and Fandom footer
fandom.com##.global-footer
fandom.com###mixed-content-footer

! Right sidebar
fandom.com##.page__right-rail

! When you highlight text
fandom.com###highlight__sticky-container

! Explore tab
fandom.com##.explore-menu.wds-dropdown

! Search
fandom.com##.search-seeding

! Edit buttons
fandom.com##.page-side-tool.page-side-edit
fandom.com##.mw-editsection
```

**Comment by JohnyP36** [comment]
My first response it that is may be the best to report this to uBlock (- annoyances) filter list. If they decline it, we could start a template or add the rules to an existing one.

**Comment by xvello** [comment]
Hello @lightbulbmeow, thanks for the suggestion!

I agree with @JohnyP36's reminder that our corpus should not overlap with the builtin lists, and that annoyance rules should indeed be directed there preferably.

On this case, I don't think they'll all be accepted though, as there's rules to hide the search bar, the edit button... things that many people will want to keep. I think a configurable template for these rules would indeed fit this project pretty well. I'll look into it this weekend unless another contributor gets around to it in the meantime.

**Comment by JohnyP36** [comment]
Here are my findings

>  Yellow sidebar on the left  

Only the first works on my side. Also, although the sidebar is blocked you will still see another yellow bar which I can't remove.

> The "wikia bar" on the bottom-right corner that follows you as you scroll down the page
> "Fan Feed" and Fandom footer at the very bottom of the page
> The tooltip that pops up when you try to highlight text
> "Explore" tab on the header bar
> "Top Trending Searches" when you open search
> Edit buttons on the page
> The right sidebar with the "Popular pages"

I don't see those elements and the rules you made I can't find in the html code of the site.  

So, or you see those elements only or partial when you are logged in or/and you are using mobile version (in which I still can't verify your rules).

**Comment by lightbulbmeow** [comment]
Sorry for the confusion @JohnyP36, I think you're looking at the homepage. By fandom.com, I meant any of the wiki pages under the domain. For example, https://minecraft.fandom.com/wiki/Creeper

Here are screenshots that might help:

Before adding filters
![Screenshot_20230705_164852](https://github.com/letsblockit/letsblockit/assets/62456216/abe0da10-ab8c-4517-91a9-93e765d348df)
After adding filters
![Screenshot_20230705_165254](https://github.com/letsblockit/letsblockit/assets/62456216/a8b7c418-d51b-4905-a665-e8b1c17e133c)

I also thought of suggesting this to the uBlock filter list. But as @xvello mentioned, I think most of the features I mentioned above are things that many people might want to keep, so they might not be suitable for the 'big' filter list and be better as configurable options instead.

**Comment by lightbulbmeow** [comment]
> as there's rules to hide the search bar, 

To clarify, the filter only hides the "Top Trending Searches" when you open the search bar. It does not remove the search bar itself.

**Comment by JohnyP36** [comment]
> Sorry for the confusion @JohnyP36, I think you're looking at the homepage. By fandom.com, I meant any of the wiki pages under the domain. For example, `https://minecraft.fandom.com/wiki/Creeper`

Thanks, this will help a lot.

**Comment by BPower0036** [comment]
@JohnyP36 @lightbulbmeow to counter that yellow border at fandom home page, add: `fandom.com##body:style(border-left: none !important)`

**Comment by xvello** [comment]
Heya @lightbulbmeow, thanks again for your contribution! The new template is deployed and available at https://letsblock.it/filters/fandom-cleanup

Don't hesitate to reach out if you have other suggestions!
