### ISSUE TITLE
YouTube Interface Cleanups: Hide Reaction control panel

### ISSUE THREAD

**Issue by lichtmetzger** [letsblockit/letsblockit#492]
### What filter does this issue target?

https://letsblock.it/filters/youtube-cleanup

### What changes should be made?

The new reaction bar sometimes hovers over the chat messages and hides part of them, which is a terrible design.
Give us an option to hide it! :)

![image](https://github.com/letsblockit/letsblockit/assets/1711691/f9c6dd39-55b6-4d4d-a3d2-3f82a4cad65e)

### Did you write a uBlock filter solving this?

youtube.com##.yt-reaction-control-panel-overlay-view-model

**Comment by JohnyP36** [comment]
As you can see I made a PR, but I do not have this new lay-out. Thus, I can't and haven't tested your rule

**Comment by lichtmetzger** [comment]
Thank you! 🥳

**Comment by xvello** [comment]
Hey @lichtmetzger, thanks for the idea and the read-to-use rule!

The change is currently deploying and should be available in a couple of minutes. I'll add you to our contributor list tonight, the CI for it seems broken.
