### ISSUE TITLE
Block Reels and Short Videos on Facebook

### ISSUE THREAD

**Issue by stevesong** [letsblockit/letsblockit#497]
### What website(s) would this filter apply to?

https://www.facebook.com/

### What content should be blocked?

I would like to block the short videos on Facebook.  They are a mindless distraction.

![image](https://github.com/letsblockit/letsblockit/assets/857180/11e2cf40-84a3-4c40-88ac-b6267495f0fa)

**Comment by xvello** [comment]
Hello @stevesong, thanks for taking the time to suggest this template, and don't hesitate to suggest others.

I am closing this one as out-of-scope, as Meta's websites are not and will not be supported by this project. This is indicated in [our contribution guidelines](https://letsblock.it/help/contributing).
