### ISSUE TITLE
People Also Ask leaking through

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#500]
### What filter does this issue target?

https://letsblock.it/filters/google-search-cleanup

### What changes should be made?

"People also ask" is no longer being blocked by the "Google Search: interface cleanups" filter despite "Hide the "_People also ask_" contextual content" being checked (all filters are checked and updated.

### Did you write a uBlock filter solving this?

No, using the existing filter.

### Additional notes

![2023-07-08](https://github.com/letsblockit/letsblockit/assets/32925097/fc50a330-2798-4f07-82fa-132cf7d1c45c)

![2023-07-08 (1)](https://github.com/letsblockit/letsblockit/assets/32925097/cc3e18e9-377b-487c-ac6c-a10f4ae7a69c)

**Comment by xvello** [comment]
Hello @3DWORX-SA and thanks for the detailed report. Could you please try the following rule?

```adblock
www.google.com###rso div.related-question-pair:upward(div[jscontroller])
```

**Comment by 3DWORX-SA** [comment]
I presume you meant filter, not rule.
But it works as a filter. Thanks!

**Comment by xvello** [comment]
Heya @3DWORX-SA 

The fix has just been deployed! Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it!

**Comment by 3DWORX-SA** [comment]
Great, thanks Xavier.
