### ISSUE TITLE
Block new music released on YouTube this week

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#502]
### What website(s) would this filter apply to?

youtube.com

### What content should be blocked?

YouTube is showing a new section that lists new music released this week. I've not seen this before.

![2023-07-09](https://github.com/letsblockit/letsblockit/assets/32925097/5eb6fac2-cb4e-4921-99e2-019748aadabb)

### What options should be offered?

A filter to block this section for poeple who are not interested in music on YouTube.

### Did you write a custom uBlock filter already?

No.

**Comment by JohnyP36** [comment]
Although I have not the exact same banner, the banner I see is blocked by uBlock filters. 

Also, as you are logged in you can discard this message. (Click on the cross at the right top of the banner). 

If the last doesn't work properly and the message keeps showing, I would advise first reporting it to uBlock.

**Comment by xvello** [comment]
Heya @3DWORX-SA, is that on the homepage? I don't have much experience with that page, I only use the subscriptions page.

Looks like there's no semantic information to target this specific section, and there's so many of them that maintaining specific options would be a nightmare. The following rule should remove all these dismissable sections, only keeping the classic grid:

```adblock
www.youtube.com##ytd-browse[page-subtype="home"] ytd-rich-section-renderer
```

**Comment by 3DWORX-SA** [comment]
Hi - it's the home page but dismissing the message (X) seems to work until logging out, clearing cookies and logging in again, but it doesn't always appear immediately - perhaps only after having searched for specific music or having visited a music video page. I'll try the code and see how it works.

I thought I had got the correct semantic info for such a message - I got the best I could, but learning... If you can give me some tips I'll try send better info in future. Thanks

**Comment by xvello** [comment]
> I thought I had got the correct semantic info for such a message - I got the best I could, but learning... If you can give me some tips I'll try send better info in future. Thanks

The fault is not yours, it's the website's authors'. All of these homepage sections use the exact same markup, so the only option would be to match on the section's title, which I refuse to do because our userbase is international. That's why I suggested a rule to remove them all, as they are all equally noisy in my opinion.

**Comment by 3DWORX-SA** [comment]
Thanks Xavier
