### ISSUE TITLE
Hide Survey Popup on Fandom

### ISSUE THREAD

**Issue by hianick** [letsblockit/letsblockit#509]
### What filter does this issue target?

Fandom Cleanup https://letsblock.it/filters/fandom-cleanup

### What changes should be made?

![image](https://github.com/letsblockit/letsblockit/assets/93717800/e7ae86b8-5f15-4e9a-af79-6c970a12daf9)

Survey popup in the bottom left. 

### Did you write a uBlock filter solving this?

fandom.com##.notifications-placeholder

### Additional notes

This fixes it for me on a bunch of random pages I tested it on, but I'm not familiar with ublock filters. Figure I'd mention it though.

**Comment by xvello** [comment]
Hello @hianick, thanks for your contributions, I'm opening https://github.com/letsblockit/letsblockit/issues/509 to implement it.
