### ISSUE TITLE
DuckDuckGo and Brave .onion addresses

### ISSUE THREAD

**Issue by m3thm4th** [letsblockit/letsblockit#523]
The .onion addresses of DuckDuckGo and Brave should be added

https://duckduckgogg42xjoc72x3sjasowoarfbgcmvfimaftt6twagswzczad.onion

https://search.brave4u7jddbv7cyviptqjc7jusxh72uik7zt6adtckl5f4nwy2v72qd.onion

**Comment by xvello** [comment]
Heya @m3thm4th, this is now implemented at https://letsblock.it/filters/search-results, as sub-option when the relevant search engine is selected.
