### ISSUE TITLE
fandom-cleanup: background is too small with "Hide yellow sidebar" enabled

### ISSUE THREAD

**Issue by Visne** [letsblockit/letsblockit#531]
### Describe the bug

When enabling the Fandom "Hide yellow sidebar" filter, the background is moved to the left. Sometimes it becomes too small because of this, and it leaves an empty space to the right side.

### Your browser and device

Firefox desktop

### Reproduction steps

1. Visit [this page](https://create.fandom.com/wiki/Cogwheel), without the Fandom "Hide yellow sidebar" filter enabled
2. Note that there is no black strip on the right side
3. Enable the Fandom "Hide yellow sidebar" filter
4. Refresh the fandom page
5. Note that there is a black strip to the right

### Expected behavior

The background image should fill up the entire page.

### Additional notes

Perhaps this can be fixed by changing some CSS, to stretch the background over the entire width?

**Comment by xvello** [comment]
Hello @Visne, thanks for the report!

@lightbulbmeow would you have a moment to look into this? It looks like the `fandom-community-header__background` div has a `width: calc(100% - 66px);` that needs to be neutralized too.

**Comment by lightbulbmeow** [comment]
@xvello Seems like adding the line
`fandom.com##.fandom-community-header__background:style(width: 100% !important)`
should fix it

**Comment by xvello** [comment]
Thanks @lightbulbmeow for confirming!

The fix has just been deployed! Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it!
