### ISSUE TITLE
Add notifications to youtube shorts filter

### ISSUE THREAD

**Issue by Kloxified** [letsblockit/letsblockit#543]
### What filter does this issue target?

Youtube Shorts

### What changes should be made?

![image](https://github.com/letsblockit/letsblockit/assets/66909922/bd352e2a-3d1f-42a9-a461-b3dc90b94213)

Youtube Shorts are currrently not removed from the notifications tab.

### Did you write a uBlock filter solving this?

No sadly.

### Additional notes

If this could be added that would be amazing! Thank you for all the amazing work yall do.

**Comment by xvello** [comment]
Hello @Kloxified, thanks for opening this issue!

I don't use this feature, so cannot reproduce, but I'll be happy to review and merge a PR that implements it.

BTW, filtering out notifications can create a confusing situation where the notification icon is triggered, but the list is empty (if there's only filtered items in the new notifications). We won't be able to hide that icon.

**Comment by xvello** [comment]
The fix has just been deployed! Your browser will get the update in less than 24h, but you can [manually refresh your list](https://letsblock.it/help/refresh-list) right now to grab it!
