### ISSUE TITLE
filter out old YT vids

### ISSUE THREAD

**Issue by NoAimy** [letsblockit/letsblockit#548]
### What website(s) would this filter apply to?

YouTube

### What content should be blocked?

Need a Time Filter for the YT Subscrition Box. To hide every video, which is older like half a year ore older.

### What options should be offered?

ability if you want to block from a few months or from years? some may like to keep older videos in their Subscription Box.

### Did you write a custom uBlock filter already?

no

### Additional notes

just want to have yt clean again, like years ago, when it showed only the new unseen videos.

**Comment by BPower0036** [comment]
Just a note. I remember that @xvello once said to me that he didn't want to hide the short in YT Subsciption.
Let first see what he thinks of this idea.

**Comment by JohnyP36** [comment]
If you mean with `Subscription Box` the box that pops up when you click on the notification bell, I have good news: YouTube will remove videos from there if they stay there for to long (somewhere after 2 or 3 months - is my experience).

**Comment by xvello** [comment]
Hello @NoAimy, thanks for using the project and suggesting an improvement!

This topic has already been discussed in https://github.com/letsblockit/letsblockit/issues/349 and https://github.com/letsblockit/letsblockit/issues/474 : such filtering would be extremely brittle and depend on the user's display language.

I suggest you test a few [alternative interfaces for youtube] (https://github.com/mendel5/alternative-front-ends#youtube) instead. These interface have access to more metadata than our rules do, and could easily implement this kind of filtering.
