### ISSUE TITLE
Age popup

### ISSUE THREAD

**Issue by hianick** [letsblockit/letsblockit#550]
### What filter does this issue target?

https://letsblock.it/filters/fandom-cleanup

### What changes should be made?

This parent/child popup only shows on some pages, not all. The screenshot is from https://minecraft.fandom.com/wiki/Key_codes.

![image](https://github.com/letsblockit/letsblockit/assets/93717800/d398da86-fac8-417d-9f2d-d28e8181c325)

### Did you write a uBlock filter solving this?

fandom.com##.AgeGateDialog-module_overlay__aPtu5.Modal_overlay__7pQwi
fandom.com###age-gate

### Additional notes

As for the 2nd line, there are 4 cosmetic filters that show for the element picker, and all 4 work, but the "age-gate" one sounds the most generic. There also is a network filter that shows up as well, but I don't know how to incorporate that into a filter.

**Comment by xvello** [comment]
Heya @hianick,

Thanks to @JohnyP36, the update has just been deployed! It is disabled by default, so you'll have to enable it at https://letsblock.it/filters/fandom-cleanup then [manually refresh your list](https://letsblock.it/help/refresh-list) to grab it!

Thanks for your contribution!
