### ISSUE TITLE
Hide GitHub Explore Repositories section on the homepage

### ISSUE THREAD

**Issue by datsudo** [letsblockit/letsblockit#552]
### What filter does this issue target?

GitHub: interface cleanups

### What changes should be made?
![image](https://github.com/letsblockit/letsblockit/assets/76833632/c0e467ad-8246-46db-8230-454d2cce8790)

### Did you write a uBlock filter solving this?

```
! 2023-09-21 https://github.com
github.com##.rounded-2.p-3.color-border-muted.border.color-bg-default.mb-5
```

**Comment by BPower0036** [comment]
The trending and recommended rule for the homepage is needless, since one can filter it out themselves via the filter seetings on the homepage.

**Comment by datsudo** [comment]
> The trending and recommended rule for the homepage is needless, since one can filter it out themselves via the filter seetings on the homepage.

Oh, I didn't notice that. I removed the first filter now

**Comment by xvello** [comment]
Heya @datsudo, thanks for your contribution, and thanks to @BPower0036 for opening the PR. It is deployed and available at https://letsblock.it/filters/github-cleanup

Don't hesitate to suggest other improvements, and feel free to open a PR directly if you want!
