### ISSUE TITLE
Block instagram distractions

### ISSUE THREAD

**Issue by Parameter15** [letsblockit/letsblockit#559]
### What website(s) would this filter apply to?

https://www.instagram.com/

### What content should be blocked?

- Block post recommendations in explore page
- Block Suggested Posts in the main page
- Block suggestions of pages to follow
- Block Instagram reels page
- Remove scrolling issues (see https://www.reddit.com/r/uBlockOrigin/comments/15erpu6/cosmetic_filtering_effecting_infinite_scrolling/jubl6u7/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button)

### Additional notes

Just like the YouTube filters, I think theses filters for Instagram will be very useful, for desktop and mobile browsers.

**Comment by JohnyP36** [comment]
- could not found out what you mean there
 - `www.instagram.com##article:has(span):has(svg[aria-label="Close"])`
 - `www.instagram.com##article + div:has(a[href="/explore/people/"])` and `www.instagram.com##main > div > div + div > div > div:has(a[href="/explore/people/"])`
 - `www.instagram.com##svg[aria-label="Reels"]:upward(:not(main) span):has(a[href^="/reels/"])`
 - I don't have any issue with scrolling, but can you help with providing the correct rule, as there are a couple of proposed rules on reddit

NOTE: the given rules are way to vulnerable to create false positives if Instagram changes their code. To solve this language specific elements should be included in the rules, but that makes them not useful for our/this project, as we want all rules to be working for everyone.

**Comment by Parameter15** [comment]
Thank you, @JohnyP36 !

In the first topic, I meant the suggested posts in the explore/search page. [See this image](https://images.ctfassets.net/az3stxsro5h5/6YkJrpwSxlpPRnuHAWKKH6/e93a483fa4eb7c903d1cba8122bf2289/Explore_Page_on_Instagram.png?w=873&h=900&q=50&fm=webp) for instance (I found it in a website).

I'm very new to this project.  Is it possible that your filters became an official list in letsblock.it?

**Comment by JohnyP36** [comment]
We have to wait for the code owner @xvello to decide if the rule become a template on letsblock.it. 
Regarding the first topic: it's difficult to solve, as the page is a search and explore page in one. (If you are using your laptop you could see that it are two different pages)

**Comment by Parameter15** [comment]
Thanks again, @JohnyP36 !

The code `www.instagram.com##article:has(span):has(svg[aria-label="Close"])` did not work to me for blocking "suggested posts" in the home page. 

This code kinda of worked: `www.instagram.com##article:has-text(/•Follow/i)`. However, Instagram tries to load the post, so that it appears for one or two seconds, and then it is blocked, causing scrolling issues.

**Comment by JohnyP36** [comment]
Do you mean the section that comes after the post from people you are following, or just single post in between your posts?

If you mean the first one, it's almost impossible to block properly (make a non language specific rule).

**Comment by Parameter15** [comment]
Yes, the first case. Basically, I only want to see posts from pages I follow.

If it is possible to block every post after the title "Suggested Posts", my problem is solved.

**Comment by JohnyP36** [comment]
> If it is possible to block every post after the title "Suggested Posts", my problem is solved.

I can give it a try to make a rule without causing scrolling issues

**Comment by xvello** [comment]
Hello @Parameter15 and thanks for your suggestion.

Meta is a company I refuse to associate with, and as such I will not be merging any filter targeting its websites, as stated in [the contribution guidelines](https://letsblock.it/help/contributing).
