### ISSUE TITLE
Control YouTube Autoplay Default

### ISSUE THREAD

**Issue by QJKX** [letsblockit/letsblockit#563]
### What website(s) would this filter apply to?

www.youtube.com

### What content should be blocked?

YouTube defaults to autoplaying the next video.

The filter should change that to default the autoplay to off.

This is useful for watching youtube in private browsing.

### What options should be offered?

- Default Autoplay to off

### Additional notes

I searched for "autoplay" but couldn't find any mention of it in the project.

**Comment by BPower0036** [comment]
@QJKX I think it is better to try a Youtube Nonstop Addon, like you can find here: https://github.com/BPower0036/YT-Nonstop

**Comment by xvello** [comment]
Hello @QJKX, thanks for your interest in the project. As far as I know, the underlying technology we use for this project does not allow for this kind of control, as we cannot inject arbitrary javascript in the page.

Achieving this requires a fully-fledged browser extension, such as [Unhook](https://addons.mozilla.org/fr/firefox/addon/youtube-recommended-videos), that seems to support disabling autoplay.

**Comment by QJKX** [comment]
Thanks for the replies. 

I found a uBlock filter that solves my problem https://github.com/DandelionSprout/adfilt/blob/master/StopAutoplayOnYouTube.txt#L11

**Comment by BPower0036** [comment]
@QJKX The only problem with that filter is, that is als blocks the endscreen, which is a side effect not everyone may want.
