### ISSUE TITLE
uBlock filter for disabling infinite scrolling in the Short player

### ISSUE THREAD

**Issue by parigi-n** [letsblockit/letsblockit#564]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

It disables infinite scrolling in the Short player.
You can still view the first short of the list.
It's useful when you regularly get on youtube shorts from a direct link without being distracted by the recommended shorts (infinite scrolling = evil)

### Did you write a uBlock filter solving this?

www.youtube.com##ytd-reel-video-renderer~ytd-reel-video-renderer

### Additional notes

Example page: https://www.youtube.com/shorts/BmOPjifD1hE
You should not be able to go or see next short

**Comment by JohnyP36** [comment]
@parigi-n Your rule works, but to rule out false positives on other YT pages use `www.youtube.com##ytd-reel-video-renderer~ytd-reel-video-renderer:matches-path(/shorts/)`
@xvello In which template should be add this rule? `youtube-cleanup` or `youtube-shorts`?

**Comment by xvello** [comment]
Hello @parigi-n, thanks a lot for your contribution!

Let's add it to the `youtube-cleanup` template, to keep the shorts one parameter-less. I already added the contributors entry in https://github.com/letsblockit/letsblockit/pull/565

**Comment by xvello** [comment]
It's deployed at https://letsblock.it/filters/youtube-cleanup, thanks team!
