### ISSUE TITLE
Fandom cleanup filter suggestion

### ISSUE THREAD

**Issue by woodiertexas** [letsblockit/letsblockit#572]
### What filter does this issue target?

https://letsblock.it/filters/fandom-cleanup

### What changes should be made?

Fandom's "Gamespot Expert Reviews" section isn't currently blocked by the fandom cleanup filter.
![image](https://github.com/letsblockit/letsblockit/assets/17211100/81f537d2-8f81-4119-8dbc-96b18c1089e3)

### Did you write a uBlock filter solving this?

`fandom.com##.reviews`

**Comment by xvello** [comment]
Thanks for your contribution @woodiertexas! It's now available at https://letsblock.it/filters/fandom-cleanup

**Comment by woodiertexas** [comment]
You're welcome
