### ISSUE TITLE
Hacker News Darkmode

### ISSUE THREAD

**Issue by bmansfie** [letsblockit/letsblockit#578]
### What filter does this issue target?

https://letsblock.it/filters/hackernews-darkmode

### What changes should be made?

Alternative hackernews darkmode I wrote.  I've been using it for months now and I haven't seen any further issues with it.

### Did you write a uBlock filter solving this?

news.ycombinator.com##body:style(background: black)
news.ycombinator.com##td:style(color: #fafafa !important)
news.ycombinator.com##table:style(background-color: #120F0D)
news.ycombinator.com##div.toptext:style(color: #fafafa)
news.ycombinator.com##span.c00:style(color: #fafafa !important)
news.ycombinator.com##span.c5a:style(color: #d0d0d0 !important)
news.ycombinator.com##span.c73:style(color: #b0b0b0 !important)
news.ycombinator.com##span.c82:style(color: #9a9a9a !important)
news.ycombinator.com##span.c9c:style(color: #737373 !important)
news.ycombinator.com##span.cae:style(color: #5a5a5a !important)
news.ycombinator.com##span.cbe:style(color: #4a4a4a !important)
news.ycombinator.com##span.cce:style(color: #3a3a3a !important)
news.ycombinator.com##span.cdd:style(color: #2f2f2f !important)
news.ycombinator.com##a:style(color: #ffa000 !important)
news.ycombinator.com##span#karma:style(color: #faa000 !important)
news.ycombinator.com##span.pagetop:style(color: #fafafa !important)
news.ycombinator.com##textarea:style(color: #fafafa !important; background: inherit; )
news.ycombinator.com###hnmain:style(background: #120F0D !important)

**Comment by xvello** [comment]
Hello @bmansfie and thanks for your suggestion. 

I do not wish to maintain several variants, and the current rules are good enough in my book. I will close this issue, as I will not implement this, but don't hesitate to suggest other improvements.
