### ISSUE TITLE
"Killfile" for HackerNews?

### ISSUE THREAD

**Issue by OldGuyInTheClub** [letsblockit/letsblockit#595]
### What website(s) would this filter apply to?

https://news.ycombinator.com

### What content should be blocked?

I like HackerNews but would like a way to use uBlock Origin to hide subjects that don't interest me.  I believe that there is an API that describes how HN works under the hood but I don't have the skills to write my own uBO filters.  (I've tried to learn but even the tutorials require advanced knowledge of DOMs, CSS, and other involved topics.)

I'd like to create filters where I can specify keywords to exclude and have those not show up on the pages.

**Comment by Nomes77** [comment]
Can you try:
```
##.athing:has-text(battery)
##.athing:has-text(battery) + tr:not(id)
##.athing:has-text(battery) + tr:not(id) + .spacer
```

**Comment by OldGuyInTheClub** [comment]
It worked!  I created a few filters replacing the text in the lines above as needed.  Those items disappear from HackerNews pages.  Thank you, very much!

If it is not too much trouble, can you elaborate on how you came up with this solution?  Before posting I was using the Inspector to see if I could come up with a filtering idea but could not.    I have not seen '.athing' before.  If it is part of the webpage, I don't see it in the Inspector.  Is it a part of uBO?  

I would like to "crack the code" of uBO filtering.

**Comment by Nomes77** [comment]
I used the browser inspecter (on windows 10 `Ctrl + Schift + I`). And then tested it with the uBO inspector. It did this this way, because the classnames uBO gived, were not workable with.

**Comment by OldGuyInTheClub** [comment]
Ah, ok.  I use Firefox on a Mac.  I tried the uBO inspector as you suggested and see an entry with .athing.  When I select that, the subject line on a message highlights.  In the past I have used the uBO Inspector to block page elements but never understood what was going on behind the scenes.  I will definitely explore this and try to create my own filters!
