### ISSUE TITLE
Google-search-cleanup: Hide instant answer / rich context result section in the search box

### ISSUE THREAD

**Issue by opzch** [letsblockit/letsblockit#611]
### What filter does this issue target?

https://letsblock.it/filters/google-search-cleanup

### What changes should be made?

Try to hide the whole section for huge "rich" autocomplete context results / instant answers popping out to the right in the search box when you edit or start typing a new search on the search result page (desktop) https://www.google.com/search?q=%s.

![image](https://github.com/letsblockit/letsblockit/assets/99139463/9c02be94-70a6-4002-9953-60379eb26713)

The result often changes several times depending on the query and its length before you finish typing, also changing the width of the search box (expanding to the right and back) and moving the search action buttons (clear | voice search/lens/search):

https://github.com/letsblockit/letsblockit/assets/99139463/a0b29300-f4a8-4fb5-b929-07d06b9763bc

Besides, this section often hosts People also search for's:
![image](https://github.com/letsblockit/letsblockit/assets/99139463/011d9665-fe80-4569-b436-f1515a5558ff)

### Did you write a uBlock filter solving this?

No.

I notice that even if hide the block with some rule (for example, generated by the element picker/element hiding helper), the search box will still expand next time; probably needs a more complex solution

### Additional notes

Activated and installed all of: https://letsblock.it/filters/google-search-cleanup

Checked with:
Chromium 120.0.6099.199 + uBlock origin 1.54.0
Chromium 120.0.6099.199 + AdGuard 7.16.0
Librewolf 121.0-1 + uBlock origin 1.54.0
Librewolf 121.0-1 + AdGuard 7.16.0

**Comment by Nomes77** [comment]
Unfortunately, I cannot reproduce it. Maybe another @letsblockit/contributors can?

**Comment by JohnyP36** [comment]
I can't reproduce the following
 - Hide most rich-content results (images, stories, businesses...) in the web search
 - Hide the "People also ask" contextual content
 - Hide the "Related searches" bottom content
 - Hide the "People also search for" popup shown when returning to results
 - Hide the "Similar searches" contextual content in image searches 

All the rules in the template, which can be seen below work on my side.
```adblock
www.google.*###rcnt > div:first-of-type:not([id]) > div:has(g-more-link,g-scrolling-carousel,g-img)
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(g-more-link,g-section-with-header)
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(div[role="heading"]+g-scrolling-carousel)
www.google.*###kp-wp-tab-overview > div:has(g-more-link,g-section-with-header,#media_result_group)
www.google.*###rso div.related-question-pair:upward(div[jscontroller])
www.google.*###botstuff #bres
www.google.*###rso div.g div[jscontroller][id^="eob_"]
www.google.*###rso div.MjjYud:has(div[jsname="Cpkphb"] a[href^="/search?"])
www.google.*##div.isv-r[data-rfg]
```

But if you add `||google.*/search$removeparam=/^(client)=/,domain=~consent.google.com` to your list, you will definitely not see any other content then search results in your search box. Although I can't verify google also uses the search box for "People also search for's ".

**Comment by xvello** [comment]
Heya @opzch,

The new option has just been deployed, you'll find it in https://letsblock.it/filters/google-search-cleanup
Thanks @Nomes77 and @JohnyP36 for the contribution!
