### ISSUE TITLE
Feature: Add Comments into custom-built lists

### ISSUE THREAD

**Issue by realAzazello** [letsblockit/letsblockit#613]
Typically built lists are un-commented:
```
www.google.*###rso div.related-question-pair:upward(div[jscontroller])
www.google.*###botstuff #bres
www.google.*###rso div.g div[jscontroller][id^="eob_"]
www.google.*###rso div.MjjYud:has(div[jsname="Cpkphb"] a[href^="/search?"])
```
Would be helpful to have comments added, using the pre-existing text description for the choices box (example):
```
! Let's Block It - Google Search: interface cleanups :: https://letsblock.it/filters/google-search-cleanup
! Hide the "People also ask" contextual content
www.google.*###rso div.related-question-pair:upward(div[jscontroller])
! Hide the "Related searches" bottom content
www.google.*###botstuff #bres
```

Sure, this is minor, but very helpful.

Especially in cases where the notation contains two or more filters:
```
! Hide the "People also search for" popup shown when returning to results
www.google.*###rso div.g div[jscontroller][id^="eob_"]
www.google.*###rso div.MjjYud:has(div[jsname="Cpkphb"] a[href^="/search?"])
```

**Comment by xvello** [comment]
Hello @realAzazello, thanks for reaching out!

That information is already available if you click the `Template source` link on the right-side menu. It will take you to [the template source file](https://github.com/letsblockit/letsblockit/blob/070f66193d035eb398a39979ec6e3048ac423c23/data/filters/templates/google-search-cleanup.yaml#L45-L55), that is a simple handlebars format. You'll find that some template sources hold additional comments in `{{ ! }}` section, when they help with maintenance.

My main focus right now is to reduce the effort needed to contribute templates, and asking contributors to consistently maintain these comments would go against this goal for no significant gain to our main userbase.
