### ISSUE TITLE
SoundCloud — Hide comments

### ISSUE THREAD

**Issue by veyndan** [letsblockit/letsblockit#614]
### What website(s) would this filter apply to?

https://soundcloud.com/c0ncernn/s3-e2

### What content should be blocked?

The comments on all song waveforms across the whole site.

<img width="836" alt="Screenshot 2024-01-12 at 01 36 56" src="https://github.com/letsblockit/letsblockit/assets/6900601/1f7c6e19-3dcb-4c94-bbfe-eda05d4bead0">

### What options should be offered?

- Hide comments on the song page itself.
- Hide the "Write a comment" textarea.

<img width="876" alt="Screenshot 2024-01-12 at 01 39 50" src="https://github.com/letsblockit/letsblockit/assets/6900601/85715af7-83b1-4a1a-ab2e-934bcc1093e1">

### Did you write a custom uBlock filter already?

I just wrote a custom uBlock filter for the blocking of comments on waveforms:

```
soundcloud.com##.waveformCommentsNode,.commentPlaceholder,.commentPopover
```

**Comment by xvello** [comment]
Hello @veyndan, thanks for the suggestion! I'll create a new `soundcloud-comments` template with that shortly.

If you want to tinker with it yourself and open a PR, feel free to fork the repo and copy the https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/woolworths-cleanup.yaml template as a starting point.

**Comment by xvello** [comment]
Thanks a lot for your contribution @veyndan! It's deployed and available at https://letsblock.it/filters/soundcloud-comments
