### ISSUE TITLE
Short videos showing up repeatedly in YouTube despite shorts filter being installed

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#621]
### What filter does this issue target?

https://letsblock.it/filters/youtube-shorts

### What changes should be made?

Investigate how shorts are bypassing filter. I see multiple videos shorter than a minute - most are about 35 seconds long or shorter.

### Did you write a uBlock filter solving this?

No

**Comment by JohnyP36** [comment]
@3DWORX-SA Can you provide information on where this does occur on youtube: when searching, on homepage, ...?

**Comment by 3DWORX-SA** [comment]
This is on the home page. There are multiple short videos under 35 seconds in duration scattered amongst the longer videos, even though the Youtube short filter is enabled.

**Comment by JohnyP36** [comment]
> This is on the home page. There are multiple short videos under 35 seconds in duration scattered amongst the longer videos, even though the Youtube short filter is enabled.

I will take a look when I have time.

**Comment by Nomes77** [comment]
I think that those are just normal videos which are not marked as shorts, but still are short.
So we then have to block videos with durations under the one minute.

**Comment by xvello** [comment]
Heya @3DWORX-SA could you please confirm whether these videos are indeed shorts, or just vertical videos that have not been tagged as shorts? Please click on one of them and copy the URL.

If these videos are indeed no properly flagged as shorts, it's a known limitation of our rules. We could indeed revive the filter on duration, but that might be transient due to one creator figuring out the upload.

**Comment by 3DWORX-SA** [comment]
They are short in duration - in the range of 10 to 35 seconds mostly. I did not previously have many of these very short duration videos showing up in the normal home page feed. Here are some examples:
https://www.youtube.com/watch?v=jNTgj7SBHB4
https://www.youtube.com/watch?v=UShD03eG9IU
https://www.youtube.com/watch?v=yycL_wsIudE
https://www.youtube.com/watch?v=ywmowze7WK0
https://www.youtube.com/watch?v=KWSsjhHA0IM
https://www.youtube.com/watch?v=YqwaQSWheNQ
https://www.youtube.com/watch?v=Foi0jLpAEKM
https://www.youtube.com/watch?v=uuQf9OgVokY
https://www.youtube.com/watch?v=eB69Hjyy6uY

**Comment by JohnyP36** [comment]
> They are short in duration - in the range of 10 to 35 seconds mostly. I did not previously have many of these very short duration videos showing up in the normal home page feed. Here are some examples:

The lay-out is not in accordance with YT Shorts; for me this seems like just very short videos. But short videos are not the same as Shorts

**Comment by xvello** [comment]
Thanks for your quick answer! These are not "real YT shorts", so they fall outside of the scope of the `youtube-shorts` template, but we could revive the duration rules under a different template, or an option to this template. @letsblockit/contributors can I leave you the final decision on this?

**Comment by Nomes77** [comment]
Homepage: `www.youtube.com##ytd-browse[page-subtype="home"] ytd-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d)$/):upward(ytd-rich-item-renderer)`
Subscription: `www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d)$/):upward(ytd-rich-item-renderer)`, `www.youtube.com##ytd-browse[page-subtype="subscriptions"] ytd-video-renderer ytd-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d)$/):upward(ytd-item-section-renderer)`
Search: `www.youtube.com##ytd-search ytd-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d)$/):upward(ytd-video-renderer)`
Trending: `www.youtube.com##ytd-browse[page-subtype="trending"] ytd-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d)$/):upward(ytd-video-renderer)`
Suggestion sidebar: `www.youtube.com##ytd-watch-next-secondary-results-renderer ytd-thumbnail-overlay-time-status-renderer span:has-text(/^(0:\d\d)$/):upward(ytd-compact-video-renderer,ytd-shelf-renderer)`

**Comment by JohnyP36** [comment]
@Nomes77 , Why not use `ytd-thumbnail #time-status >` instead of `ytd-thumbnail-overlay-time-status-renderer`? It has fewer positive hits with uBlock  and also hides the element (at least on the homepage)?

@xvello , For some reason the regex doesn't work well on my side, as uBlock can't find anything while there are videos that meet those requirements.

**Comment by 3DWORX-SA** [comment]
Thanks all for confirming these are not really shorts but just short videos being served up. I assume it's an algorithmic change as I had not seen so many before.
It would be useful to have a separate rule that can block videos shorter than, say, 60 seconds, if you are able to make such a thing.
Thanks folks!

**Comment by xvello** [comment]
New template is deployed at https://letsblock.it/filters/youtube-video-duration

**Comment by 3DWORX-SA** [comment]
Thanks for the work to create this template everyone.
I implemented two rules:

  *   Exclude videos shorter than 1 minute: 0:\d\d
  *   Exclude videos longer than one hour: 1:\d\d:\d\d|\d\d:\d\d:\d\d

I don't see any short vids on my home page, but this 1h36m video displayed on the home page: https://www.youtube.com/watch?v=701pwm78Q90

Can these two rules work with one another?
Thanks

**Comment by JohnyP36** [comment]
For videos longer than one hour (infinite) you need `[1-9]:\d\d:\d\d|\d\d:\d\d:\d\d)` for that.
Or as you wish, combine your two rules in one: `0:\d\d|([1-9]|\d\d):\d\d:\d\d`.
