### ISSUE TITLE
YouTube: filter out videos you already watched - separate subscriptions and channel pages filters

### ISSUE THREAD

**Issue by 3DWORX-SA** [letsblockit/letsblockit#624]
### What filter does this issue target?

https://letsblock.it/filters/youtube-watched

### What changes should be made?

Can the "Hide watched videos on the subscriptions and channel pages" be separated into two separate items on the "YouTube: filter out videos you already watched" filter?

### Did you write a uBlock filter solving this?

No

### Additional notes

Motivation:

- View all the videos, watched and unwatched, when selecting a specific channel (or choose to hide these)
- But filter/hide watched videos when selecting the https://www.youtube.com/feed/subscriptions page

**Comment by xvello** [comment]
Merged and deployed, thanks for the idea!
