### ISSUE TITLE
Google-search-cleanup: Block zero-prefix suggestions with recommended content

### ISSUE THREAD

**Issue by opzch** [letsblockit/letsblockit#635]
### What website(s) would this filter apply to?

Google.*

### What content should be blocked?

When you click the box on Google's main page, it sometimes loads a drop-down list infested with "Trending searches" (content depends on the region that Google assigns to the IP address and/or account):

<details>
<summary>Trending searches</summary>

![1](https://github.com/letsblockit/letsblockit/assets/99139463/e5a9df02-0f36-4c10-bb0e-c7221baf4bbf)

</details>

The same happens when you clear the existing search query on a results page and wait a second:

<details>
<summary>Zero-prefix trending searches</summary>

![2](https://github.com/letsblockit/letsblockit/assets/99139463/f264fe48-8852-471f-a46c-b9b210363ae9)

</details>

Sometimes (depending on your privacy settings and the query), when you perform several searches, clear an existing search, and remove focus from the form, "Related to recent searches" is loaded instead.

<details>
<summary>Related to recent searches</summary>

![3](https://github.com/letsblockit/letsblockit/assets/99139463/2fe26347-1da9-4571-8306-30e6effc860e)

</details>

And two more annoying variations on mobile:
<details>
<summary>On the main page:</summary>

![4](https://github.com/letsblockit/letsblockit/assets/99139463/eba617dc-2af7-4c6b-855d-bc30a1e39552)

</details>

<details>
<summary>In the search box when focused, after previous search queries</summary>

![5](https://github.com/letsblockit/letsblockit/assets/99139463/73597836-1b50-4744-bfd1-8d177a6af89a)
</details>
### What options should be offered?

An option to hide zero-prefix suggestions.
Zero-search is always an unrelated distraction, and rewritten past search queries essentially are "People also search for" and "Related searches", placed in the search box this time.

### Did you write a custom uBlock filter already?

I'm not sure.

Zero-suggestions are returned to requests with empty ?q= to URLs like these:
https://www.google.com/complete/search?q=&cp=0&client=gws-wiz&xssi=t&gs_pcrt=2&hl=en-US&authuser=0&psi=UI27Zfq8LPO2hbIPr8qB0A8.1706790212438&dpr=1&nolsbt=1
https://www.google.com/complete/search?q=&cp=0&client=gws-wiz&xssi=t&gs_pcrt=2&hl=de&authuser=0&psi=O467ZbuaPPSthbIPm-CHuAY.1706790445992&dpr=1&nolsbt=1
https://www.google.com/complete/search?q&cp=0&client=mobile-gws-wiz-serp&xssi=t&gs_pcrt=undefined&hl=en-FR&authuser=0&pq=deadline&psi=HKm7ZamzA63-7_UP9K6pyAk.1706797345064&dpr=1
https://www.google.com/complete/search?q&pq&cp=0&client=mweb-insp&xssi=t&dpr=2

- Checking traffic on /complete/search* and aborting unsolicited requests without any query prevents the section from being displayed without layout breakage.
-  `||google.*/complete/search?q&cp=0$domain=google.*,important` seems to block trending searches on desktop
-  `||google.*/complete/search?q&pq&cp=0$domain=google.*,important` on mobile

### Additional notes

It has been around for years: https://superuser.com/questions/1687163/how-do-i-get-rid-of-trending-searches-in-firefox-desktop-when-using-google-searc

While it is possible to disable it in https://www.google.com/preferences#tabVal=1 , it becomes too annoying to set this every time or be presented with the selection each time you clear cookies / open a new profile / incognito window / switch browsers, etc. And there seem to be no user scripts to set the preference automatically.

If Google cannot identify your circle of interest, language, or location (for example, if you don't sign in and use a clean VPN IP not shared with anyone), the zero-prefix section probably will not appear (as well as your address and local search results), except for "Related recent searches".

<details><summary>Filter config:</summary>
Activated and installed all of: https://letsblock.it/filters/google-search-cleanup

Checked with:
Chromium 121.0.6167.140 + uBlock origin 1.55.0
Chromium 121.0.6167.140 + AdGuard 7.16.0
Librewolf 122.0-2 + uBlock origin 1.55.0
Librewolf 122.0-2 + AdGuard 7.16.0

Chromium 120.0.6099.237 + AdGuard 4.4
Iceraven 2.15.1 + uBlock origin 1.55.0
</details>

**Comment by xvello** [comment]
Hello @opzch, thanks for your contribution.

These rules seem to work fine, let's add them! I'll open the PR in a few days, but feel free to open one if you want to modify https://github.com/letsblockit/letsblockit/blob/main/data/filters/templates/google-search-cleanup.yaml

**Comment by xvello** [comment]
It is deployed and available at https://letsblock.it/filters/google-search-cleanup, thanks a lot for the idea!
