### ISSUE TITLE
Youtube Channel Blocker

### ISSUE THREAD

**Issue by BlockSats** [letsblockit/letsblockit#639]
### What website(s) would this filter apply to?

https://www.youtube.com/results?search_query=(*search word*)

### What content should be blocked?

Youtube research : 
Topics : trading and/or crypto currency and/or Bitcoin
According to strict rules to be defined
All low quality chains, all dream sellers, all scams, etc...

### What options should be offered?

I'm not sure I understand the question "What options should be offered?"
Maybe the idea of voting for example?

### Did you write a custom uBlock filter already?

No, I've never created a list but I'd like to learn and why not host a list on a VM of my (french) Freebox for example?

### Additional notes

I would like to create a list for people researching the topics of trading and/or crypto currency and/or Bitcoin (not exaustive).
According to strict rules to be defined, all low quality chains, all dream sellers, scams, etc...
I think that channels should be subject to a vote, for example.
I'm aware of the capacity of these lists to take away revenue, but also to push content creators to upload quality; or not to upload.

I understand the difficulty of excluding certain people from search results and would like to know your opinion on my suggestion.

**Comment by xvello** [comment]
Hello @BlockSats, thanks for reaching out!

The project already has a [a template to hide videos for given channels](https://letsblock.it/filters/youtube-channel) that our users can setup to hide videos from lists and search. For our [template to hide search results for given websites](https://letsblock.it/filters/search-results), we distribute value presets maintained by our friends at [uBlock-Origin-dev-filter](https://github.com/quenhus/uBlock-Origin-dev-filter) and [BlockModReposting](https://github.com/rotgruengelb/BlockModReposting), that users can use by enabling the options at the bottom of the form. 

I'd be happy to distribute value presets for the YouTube channels template, with two conditions:
  - they are maintained in other repositories we can pull data through, as our project's contribution flow is currently pretty time-intensive
  - they are based on objective and clear criteria, not subjective opinions

The goal of this project is to empower individual to set their boundaries and curate their online experience, it is not to make curation decisions on behalf of others. I'd like to see presets that match all channels predominantly covering a given topic for example, but what you describe is too subjective to be a good fit for this project's vision. There are projects who focus on curation, such as https://www.favoree.io/ for discovering and evaluating YouTube channels, that might be a better fit your vision. 

If you want to experiment with curating and publishing an opinionated list, you could reuse our `youtube-channel` template via [our render command](https://github.com/letsblockit/letsblockit/tree/main/cmd/render). This would allow you to focus on the channel curation and reuse our work on the uBO rule management. https://github.com/notfirefox/web-filter could be a good example to get you started with.

**Comment by BlockSats** [comment]
Thank you very much for your reply.
I'm running out of time at the moment.
But I'll take a look at the links you shared with me.
I completely agree about the conditions.

Conditions could be, for example: 
-is this youtuber selling a hidden training course? 
- is he encouraging people to buy a training course?
That's the basic idea.

For the time being, I'll try to create a list for myself (when I have a bit of time) and if need be, I'll get back to you.

Thank you

Translated with DeepL.com (free version)
