### ISSUE TITLE
removing shorts

### ISSUE THREAD

**Issue by hoxishs8uwosuuui** [letsblockit/letsblockit#645]
### What website(s) would this filter apply to?

www.youtube.com 

### What content should be blocked?

blocking youtube shorts

### What options should be offered?

https://raw.githubusercontent.com/gijsdev/ublock-hide-yt-shorts/master/list.txt

**Comment by xvello** [comment]
Hello @hoxishs8uwosuuui, we already have a template for this, at https://letsblock.it/filters/youtube-shorts
