### ISSUE TITLE
Use proper comment syntax in Google Search rules

### ISSUE THREAD

**Issue by richardsavio** [letsblockit/letsblockit#649]
### What filter does this issue target?

https://letsblock.it/filters/google-search-cleanup

### What changes should be made?

The syntax for comments in the filter is wrong

Updated filter has been added below

### Did you write a uBlock filter solving this?

! Toplevel rich content above columns
www.google.*###rcnt > div:first-of-type:not([id]) > div:has(g-more-link,g-scrolling-carousel,g-img)
! Rich content in normal pages
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(g-more-link,g-section-with-header)
! "Find results on" carousel
www.google.*###rso:has(> div:nth-of-type(6)) > div:has(div[role="heading"]+g-scrolling-carousel)
! New page layout for books / movies / shows, some rich elements are not handled yet
www.google.*###kp-wp-tab-overview > div:has(g-more-link,g-section-with-header,#media_result_group)
www.google.*###rso div.related-question-pair:upward(div[jscontroller])
www.google.*###botstuff #bres
! These unfurl after clicking on a result and going back to the results page
www.google.*###rso div.g div[jscontroller][id^="eob_"]
www.google.*###rso div.MjjYud:has(div[jsname="Cpkphb"] a[href^="/search?"])
www.google.*###searchform ul[role="listbox"] > li:upward(div[jsname][role="presentation"])
www.google.*###searchform:style(--rhs-width: 0px !important; --rhs-margin: 0px !important;)
! Desktop browsers
||google.*/complete/search?q&cp=0$domain=google.*,important
! Mobile browsers
||google.*/complete/search?q&pq&cp=0$domain=google.*,important
www.google.*##div.isv-r[data-rfg]
www.google.*###rhs #kp-wp-tab-overview div[data-attrid$=" qa"]
www.google.*###rhs #kp-wp-tab-overview div[data-attrid$="review_summary"]
www.google.*###rhs #kp-wp-tab-overview div[data-attrid$="third_party_aggregator_ratings"]
www.google.*###footcnt > #fbarcnt

### Additional notes

Maybe consider removing comments entirely from the filter lists as many of the other lists don't have comments denoting what each rule does. Even in the Google Search list, it is pretty inconsistent with only some sections (toggles) having comments and rules from other sections (toggles) blending into other rules.

**Comment by xvello** [comment]
Thanks for the report @richardsavio. Fix released in v0.53.1 and deployed on the official instance.
