### ISSUE TITLE
search-results: startpage rules may need an update

### ISSUE THREAD

**Issue by linlinxza** [letsblockit/letsblockit#654]
### Describe the bug

I apply the rules and update my filter. Filtering doesn't work. Still seeing crap like Lizard's Meta domains.

### Your browser and device

Librewolf

### Reproduction steps

```bash
1.Make rules (like facebook, instagram) for Startpage
2.Update Ublock filters, or add it
3.Search for Facebook
...
```

### Expected behavior

I shouldn't be seeing any of the Lizard's domains.

**Comment by xvello** [comment]
Helllo @linlinxza, I just tested https://letsblock.it/filters/search-results and was able to hide pinterest from web and images results.

Your report does not give enough information to help you. Please copy:
  - a screenshot of the parameters you entered
  - the rules preview generated at the bottom
  - what version of uBlockOrigin you are currently using

**Comment by linlinxza** [comment]
Parameters:

![Screenshot_20240312_123125](https://github.com/letsblockit/letsblockit/assets/11242593/470d8ec9-d45e-4527-a7e7-802807f1be6a)

Rules:

![Screenshot_20240312_123225](https://github.com/letsblockit/letsblockit/assets/11242593/a286ad78-27f9-465c-8a02-7e8d01de7486)

Version of Ublock: 1.56.0

**Comment by xvello** [comment]
This looks OK. One reason why it might work randomly is if they're currently testing out a new design, and the rules will need updates for this new design. There's nothing we can do until the new design is fully released to everyone.

**Comment by linlinxza** [comment]
Ah shoot. Just that this is the best alternative I can find so I can avoid directly using Scroogle's search engine.
