### ISSUE TITLE
Please make this work on Brave with custom filtering for mobile.

### ISSUE THREAD

**Issue by linlinxza** [letsblockit/letsblockit#659]
### What website(s) would this filter apply to?

startpage.com

### What content should be blocked?

To be able to block any social media domains. Like, the Lizard's Meta domains. Or any domain of the user's choosing on mobile version of startpage.

**Comment by xvello** [comment]
Hello @linlinxza, Brave browser is not and will not be supported. See https://www.spacebar.news/stop-using-brave-browser/ for why.

**Comment by linlinxza** [comment]
> Hello @linlinxza, Brave browser is not and will not be supported. See https://www.spacebar.news/stop-using-brave-browser/ for why.

Are you serious? FYI, I am gay and don't give a crap about any of that.

Anyway, if you can recommend a browser with custom content blocking (similar to that of Ublock), then I'd ditch Brave.

**Comment by xvello** [comment]
> Are you serious?

Yes, I am dead serious. I am free to decide what I spend my unpaid hobby time on, and supporting Brave is not something I'll willing to spend time on. I encourage you to read https://snarky.ca/the-social-contract-of-open-source/

>  Every commit of open source code should be viewed as an independent gift from the maintainer that they happened to leave on their front yard for others to enjoy if they so desire; treating them as a means to and end for their open source code is unethical.

Even if I wanted to support Brave Browser, its built-in cosmetic filtering engine is missing a lot of the advanced features that our rules use.

- on Android devices, Firefox mobile supports extensions, including uBlockOrigin
- on Apple devices, the paid-for AdGuard for iOS works OK for several users, although we only support it as "best effort", see https://github.com/letsblockit/letsblockit/discussions/577
