### ISSUE TITLE
Publish an official container image

### ISSUE THREAD

**Issue by alexanderadam** [letsblockit/letsblockit#69]
[An official Docker container on Docker Hub](https://hub.docker.com/search?q=letsblockit&type=image) would be great for self hosting.
Ideally properly tagged releases would be build automatically.

**Comment by xvello** [comment]
The main blocker for this is https://github.com/xvello/letsblockit/issues/72 (simplify schema migrations on upgrade).
Once this is released, building a docker image and publishing would be pretty simple. I am already working on [building an image](https://github.com/xvello/letsblockit/blob/cf1725059a1b27712f287d7367822389552407d2/flake.nix#L32-L39) for the `render` CLI

**Comment by xvello** [comment]
Moving to a dedicated github org was mainly motivated by this issue, to use [github's container registry](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).

I'll start publishing `ghcr.io/letsblockit/render` soon, and `ghcr.io/letsblockit/server` after I work on supporting envvars for configuration.

**Comment by xvello** [comment]
Closing this issue as [container images](https://github.com/letsblockit/letsblockit/pkgs/container/server) are now built and published for each release. `v0.17.1` starts and runs OK now.

Last steps are:
  - External auth support https://github.com/letsblockit/letsblockit/issues/169 -> implemented in https://github.com/letsblockit/letsblockit/pull/180
  - Documentation, documentation, documentation. @alexanderadam would you be able to give me a hand here, by drafting and/or reviewing the self-hosting documentation?

**Comment by alexanderadam** [comment]
Woah, awesome!

>     * Documentation, documentation, documentation. @alexanderadam would you be able to give me a hand here, by drafting and/or reviewing the self-hosting documentation?

Sure, I cannot promise anything urgent but I will once I have time!

Great work! :raised_hands:
