### ISSUE TITLE
Yahoo

### ISSUE THREAD

**Issue by BPower0036** [letsblockit/letsblockit#83]
### What filter does this issue target?

search-results

### What changes should be made?

You forgot Yahoo.

https://search.yahoo.com/search?p=site%3Afacebook.com+facebook&fr2=piv-web

### Did you write a uBlock filter solving this?

`search.yahoo.com###main a[href*="{{site}}"]:upward(li)`
Works for web, images and video results

### Additional notes

There are a lot more search engine out there, which are not well known.
Like: swisscows.com, searchencrypt.com, vinden.nl, zoeken.nl.

Should I make rules for those also, or do you think it's unnecessary?

**Comment by xvello** [comment]
Hello @BPower0036 and thanks for the issue!

Are you currently using yahoo and bing, or suggesting them for exhaustivity?

As every rule costs ongoing maintenance and screen estate, I'd rather go for quality over quantity. I added the other search engines via requests from potential users, and I am happy to. I don't think there's many people in the target demographics of both yahoo search and letsblock.it.

What do you think?

**Comment by BPower0036** [comment]
@xvello No, I don't use Yahoo. 
I tought that Yahoo was a quite often used search engine.

However I **don't** think there's many people in the targer demographics of both Yahho and Letsblock.it.
